#!/usr/bin/env bash
# Rename + tag all project images in assets/imagery/
# Run from repo root: bash rename-imagery.sh

DIR="wp-content/plugins/firmengolf-events/assets/imagery"

# ── 1. Rename ────────────────────────────────────────────────────────────────
declare -A RENAMES=(
  ["64.jpg"]="frau-mit-golfschlaeger-bar.jpg"
  ["82.png"]="golfer-mann-lachend.png"
  ["85.png"]="golferin-stehend.png"
  ["86.png"]="golferin-portrait.png"
  ["87.png"]="golfer-gruppe-fairway.png"
  ["88.png"]="golfer-trio-spaziergang.png"
  ["89.png"]="golferinnen-duo-green.png"
  ["90.png"]="golfstunde-coaching-outdoor.png"
  ["Abschlag.jpg"]="golf-abschlag.jpg"
  ["Abschlag 4.jpg"]="golf-abschlag-2.jpg"
  ["Afterwork.jpg"]="firmenevent-afterwork-golf.jpg"
  ["Annaeherung.jpg"]="golf-annaeherung-green.jpg"
  ["Büro alle sind Golfen.jpg"]="buero-alle-golfen.jpg"
  ["Büro.jpg"]="buero-modern.jpg"
  ["Bürodach KI.jpg"]="buero-dachterrasse-ki.jpg"
  ["Bürodach lang.jpg"]="buero-dachterrasse-panorama.jpg"
  ["Bürodach.jpg"]="buero-dachterrasse.jpg"
  ["Club alt.jpg"]="golfclub-historisch.jpg"
  ["Club neu.jpg"]="golfclub-modern.jpg"
  ["Clubhaus 2.jpg"]="clubhaus-aussenansicht-2.jpg"
  ["Clubhaus.jpg"]="clubhaus-aussenansicht.jpg"
  ["Drivingrange.jpg"]="driving-range-uebungsplatz.jpg"
  ["Eagle Eye 2.jpg"]="golfplatz-luftaufnahme-2.jpg"
  ["Eagle Eye.jpg"]="golfplatz-luftaufnahme.jpg"
  ["Golfcart.jpg"]="golf-cart-fairway.jpg"
  ["Golfcart 2.jpg"]="golf-cart-2.jpg"
  ["Golfcart 4.jpg"]="golf-cart-3.jpg"
  ["Golfloch.jpg"]="golf-loch-flagge.jpg"
  ["Golfloch 2.jpg"]="golf-loch-flagge-2.jpg"
  ["Golfplatz.jpg"]="golfplatz-fairway.jpg"
  ["Golfplatz 3.jpg"]="golfplatz-panorama.jpg"
  ["Golfplatz von oben.jpg"]="golfplatz-drohnenaufnahme.jpg"
  ["Golfschläger.jpg"]="golfschlaeger-bag.jpg"
  ["Golfstunde.jpg"]="golf-coaching-einzel.jpg"
  ["Golfstunde 2.jpg"]="golf-coaching-einzel-2.jpg"
  ["Golfstunde 4.jpg"]="golf-coaching-gruppe.jpg"
  ["Golfstunde 5.jpg"]="golf-coaching-schwung.jpg"
  ["Golfstunde 6.jpg"]="golf-coaching-praxis.jpg"
  ["Greenkeeper.jpg"]="greenkeeper-platzdienst.jpg"
  ["Greenkeeper2.jpg"]="greenkeeper-platzdienst-2.jpg"
  ["Greenkeeper 4.jpg"]="greenkeeper-platzdienst-3.jpg"
  ["Grün.jpg"]="golf-gruen-fahne.jpg"
  ["Grün 3.jpg"]="golf-gruen-panorama.jpg"
  ["Gründer Puttet.jpg"]="gruender-putting-green.jpg"
  ["Handgepäck.jpg"]="business-reise-koffer.jpg"
  ["Handgepäck 2.jpg"]="business-reise-koffer-2.jpg"
  ["Hund.jpg"]="hund-auf-golfplatz.jpg"
  ["Hund 2.jpg"]="hund-auf-golfplatz-2.jpg"
  ["Inselgrün.jpg"]="inselgruen-signature-hole.jpg"
  ["Konzentration.jpg"]="golfer-konzentration-putt.jpg"
  ["Korb 1.jpg"]="driving-range-zielkorb.jpg"
  ["Meer.jpg"]="golfplatz-meerblick.jpg"
  ["Meer 2.jpg"]="golfplatz-meerblick-2.jpg"
  ["Mena.jpg"]="firmengolf-portrait.jpg"
  ["Nein zu Burnout.jpg"]="work-life-balance-golf.jpg"
  ["nein zu Burnout 2.jpg"]="work-life-balance-golf-2.jpg"
  ["Nein zu Burnout 3.jpg"]="work-life-balance-golf-3.jpg"
  ["Pilotencockpit.jpg"]="cockpit-fokus-analogie.jpg"
  ["Putt 3.jpg"]="golf-putt-konzentration.jpg"
  ["Putt 4.jpg"]="golf-putt-linie-lesen.jpg"
  ["Putt it in.jpg"]="golf-putt-einlochen.jpg"
  ["Putting.jpg"]="golfer-beim-putten.jpg"
  ["Puttinggrün.jpg"]="putting-gruen-uebung.jpg"
  ["Range.jpg"]="driving-range-uebung.jpg"
  ["Rangebaelle.jpg"]="driving-range-golfbaelle.jpg"
  ["Rasen.jpg"]="golfplatz-rasen-qualitaet.jpg"
  ["Rechen.jpg"]="bunker-sand-rechen.jpg"
  ["Sand.jpg"]="golf-sandbunker.jpg"
  ["Tennis.jpg"]="tennis-zu-golf-wechsel.jpg"
  ["Ubahn.jpg"]="anfahrt-oeffentlich.jpg"
  ["play your Benefit ora.png"]="firmengolf-benefit-grafik.png"
  ["Übungsgrün.jpg"]="uebungsgruen-putting.jpg"
)

echo "── Renaming files ──────────────────────────────────────────"
for OLD in "${!RENAMES[@]}"; do
  NEW="${RENAMES[$OLD]}"
  if [ -f "$DIR/$OLD" ]; then
    mv "$DIR/$OLD" "$DIR/$NEW"
    echo "  ✓ $OLD → $NEW"
  fi
done

# ── 2. EXIF / IPTC Metadata ──────────────────────────────────────────────────
# Format: "filename|ImageDescription (alt text)|Keywords"
declare -A META=(
  ["frau-mit-golfschlaeger-bar.jpg"]="Frau hält lässig einen Golfschläger in einer Bar – Golf als Lifestyle|golf,lifestyle,urban,frau,golfschlaeger"
  ["golfer-mann-lachend.png"]="Lachender Golfer mit Schläger auf dem sonnigen Fairway|golf,golfer,portrait,fairway,freude"
  ["golferin-stehend.png"]="Golferin mit Schläger steht auf dem Abschlag mit Weitblick|golf,golferin,abschlag,sport"
  ["golferin-portrait.png"]="Portrait einer lächelnden Golferin mit Schläger im Sonnenlicht|golf,golferin,portrait,lächeln"
  ["golfer-gruppe-fairway.png"]="Drei Golfer unterhalten sich beim Firmengolf-Event auf dem Fairway|firmengolf,gruppe,networking,fairway"
  ["golfer-trio-spaziergang.png"]="Drei Golfer laufen gemeinsam mit Trolleys über das Fairway|firmengolf,team,spaziergang,fairway"
  ["golferinnen-duo-green.png"]="Zwei Golferinnen stehen zusammen am Grün beim gemeinsamen Golfrunde|golf,golferin,team,gruen"
  ["golfstunde-coaching-outdoor.png"]="Golfstunde im Freien – Trainerin erklärt Schwung an eine Gruppe|coaching,golfstunde,gruppe,outdoor"
  ["golf-abschlag.jpg"]="Golfer beim kraftvollen Abschlag auf dem Golfplatz|golf,abschlag,schwung,tee"
  ["golf-abschlag-2.jpg"]="Golfer beim Abschlag vom Tee – Fokus auf den Schwung|golf,abschlag,tee,technik"
  ["firmenevent-afterwork-golf.jpg"]="Kolleginnen und Kollegen beim Afterwork Golf Event nach der Arbeit|firmengolf,afterwork,team,event"
  ["golf-annaeherung-green.jpg"]="Golfer beim Annäherungsschlag in Richtung Grün|golf,annaeherung,chip,gruen"
  ["buero-alle-golfen.jpg"]="Leeres Büro mit humorvollem Schild – alle Mitarbeiter spielen Golf|firmengolf,humor,buero,teambuilding"
  ["buero-modern.jpg"]="Modernes Büro mit offener Arbeitsatmosphäre|buero,modern,arbeit,unternehmen"
  ["buero-dachterrasse-ki.jpg"]="Bürodachterrasse mit urbanem Skyline-Blick – KI-generiert|buero,dachterrasse,urban,skyline"
  ["buero-dachterrasse-panorama.jpg"]="Panoramablick von einer Bürodachterrasse über die Stadt|buero,dachterrasse,panorama,skyline"
  ["buero-dachterrasse.jpg"]="Bürodachterrasse als Ort für entspannte Teamevents|buero,dachterrasse,event,team"
  ["golfclub-historisch.jpg"]="Historisches Golfclub-Gebäude mit Charakter und Tradition|golfclub,historisch,clubhaus,tradition"
  ["golfclub-modern.jpg"]="Modernes Golfclub-Gebäude mit zeitgemäßer Architektur|golfclub,modern,clubhaus,architektur"
  ["clubhaus-aussenansicht-2.jpg"]="Clubhaus eines Golfplatzes von außen – elegante Architektur|clubhaus,golfplatz,architektur,aussenansicht"
  ["clubhaus-aussenansicht.jpg"]="Außenansicht des Clubhauses mit Terrasse und Grünanlage|clubhaus,terrasse,gruen,aussenansicht"
  ["driving-range-uebungsplatz.jpg"]="Driving Range mit Übungsboxen für Golfer aller Niveaus|drivingrange,uebung,abschlag,training"
  ["golfplatz-luftaufnahme-2.jpg"]="Luftaufnahme eines weitläufigen Golfplatzes mit Fairways und Greens|golfplatz,luftaufnahme,vogelperspektive,fairway"
  ["golfplatz-luftaufnahme.jpg"]="Drohnenaufnahme eines Golfplatzes – Überblick über die gesamte Anlage|golfplatz,drohne,luftaufnahme,uebersicht"
  ["golf-cart-fairway.jpg"]="Zwei Golfer fahren mit dem Golf-Cart über das Fairway|golfcart,fairway,fahrt,komfort"
  ["golf-cart-2.jpg"]="Golf-Cart auf dem Golfplatz – komfortabler Transport zwischen den Löchern|golfcart,transport,golfplatz"
  ["golf-cart-3.jpg"]="Golf-Cart bei Sonnenuntergang auf dem Golfplatz|golfcart,golfplatz,sonnenuntergang"
  ["golf-loch-flagge.jpg"]="Golffahne am Loch auf dem gepflegten Grün|golf,fahne,loch,gruen"
  ["golf-loch-flagge-2.jpg"]="Golffahne im Wind – Blick auf das Loch mit makellosem Rasen|golf,fahne,loch,rasen"
  ["golfplatz-fairway.jpg"]="Gepflegtes Fairway eines Golfplatzes in satterem Grün|golfplatz,fairway,rasen,qualitaet"
  ["golfplatz-panorama.jpg"]="Panoramaansicht eines Golfplatzes mit Bäumen und weitem Himmel|golfplatz,panorama,natur,weitblick"
  ["golfplatz-drohnenaufnahme.jpg"]="Drohnenaufnahme von oben – Golfplatz mit allen 18 Löchern im Überblick|golfplatz,drohne,vogelperspektive,18loch"
  ["golfschlaeger-bag.jpg"]="Professionelles Golfschläger-Set in der Tasche bereit für das Spiel|golfschlaeger,bag,ausruestung,profi"
  ["golf-coaching-einzel.jpg"]="Professionelle Einzelstunde mit Golf-Coach auf dem Übungsgelände|coaching,einzelstunde,coach,training"
  ["golf-coaching-einzel-2.jpg"]="Golf-Coach gibt Einzelunterricht am Abschlag|coaching,einzelunterricht,technik,schwung"
  ["golf-coaching-gruppe.jpg"]="Golf-Coach unterrichtet eine Gruppe von Anfängern auf der Range|coaching,gruppe,anfaenger,range"
  ["golf-coaching-schwung.jpg"]="Golfer beim Erlernen des Schwungs unter Anleitung eines Coaches|coaching,schwung,technik,lernen"
  ["golf-coaching-praxis.jpg"]="Praxisnahe Golf-Coaching-Einheit mit direktem Feedback|coaching,praxis,feedback,training"
  ["greenkeeper-platzdienst.jpg"]="Greenkeeper pflegt das Grün für perfekte Spielbedingungen|greenkeeper,pflege,gruen,qualitaet"
  ["greenkeeper-platzdienst-2.jpg"]="Greenkeeper bei der Arbeit – Rasenpflege auf dem Golfplatz|greenkeeper,rasen,pflege,morgens"
  ["greenkeeper-platzdienst-3.jpg"]="Greenkeeper-Team sorgt für erstklassige Platzbedingungen|greenkeeper,team,platzdienst,qualitaet"
  ["golf-gruen-fahne.jpg"]="Golffahne auf dem gepflegten Grün – das Ziel jedes Lochs|golf,gruen,fahne,ziel"
  ["golf-gruen-panorama.jpg"]="Weitläufiges Grün eines Golfplatzes mit makellosem Rasen|golf,gruen,panorama,rasen"
  ["gruender-putting-green.jpg"]="Firmengolf-Gründer beim Putten auf dem Übungsgrün|gruender,putting,portrait,firmengolf"
  ["business-reise-koffer.jpg"]="Business-Reisegepäck – Golf und Geschäftsreise verbinden|business,reise,koffer,incentive"
  ["business-reise-koffer-2.jpg"]="Handgepäck für die Geschäftsreise mit Golf-Incentive|business,reise,incentive,koffer"
  ["hund-auf-golfplatz.jpg"]="Hund auf dem Golfplatz – entspannte Atmosphäre der Anlage|hund,golfplatz,entspannung,natur"
  ["hund-auf-golfplatz-2.jpg"]="Hund begleitet Golfer auf dem Fairway – hundefreundliche Anlage|hund,fairway,hundefreundlich,entspannung"
  ["inselgruen-signature-hole.jpg"]="Spektakuläres Inselgrün als Signature Hole des Golfplatzes|inselgruen,signaturehole,spektakulaer,wasser"
  ["golfer-konzentration-putt.jpg"]="Golfer in höchster Konzentration beim entscheidenden Putt|golf,putt,konzentration,fokus"
  ["driving-range-zielkorb.jpg"]="Zielkorb auf der Driving Range für präzises Kurzspiel-Training|drivingrange,zielkorb,kurzspiel,training"
  ["golfplatz-meerblick.jpg"]="Golfplatz mit atemberaubendem Blick auf das Meer|golfplatz,meer,meerblick,landschaft"
  ["golfplatz-meerblick-2.jpg"]="Golf am Meer – einzigartiges Spielerlebnis mit Meerespanorama|golfplatz,meer,panorama,traumlocation"
  ["firmengolf-portrait.jpg"]="Portrait einer Firmengolf-Teilnehmerin beim Event|portrait,firmengolf,teilnehmerin,event"
  ["work-life-balance-golf.jpg"]="Work-Life-Balance durch Golf – mentale Auszeit vom Büroalltag|worklifebalance,golf,mentalegesundheit,auszeit"
  ["work-life-balance-golf-2.jpg"]="Golf als Ausgleich zum stressigen Arbeitsalltag|worklifebalance,golf,ausgleich,burnoutpraevention"
  ["work-life-balance-golf-3.jpg"]="Nein zu Burnout – Golf als gesunde Alternative zum Arbeits-Stress|burnoutpraevention,golf,gesundheit,entspannung"
  ["cockpit-fokus-analogie.jpg"]="Piloten-Cockpit als Analogie für Fokus und Präzision im Golf|cockpit,fokus,praezision,analogie"
  ["golf-putt-konzentration.jpg"]="Golfer liest die Putlinie mit höchster Konzentration|putt,konzentration,gruen,technik"
  ["golf-putt-linie-lesen.jpg"]="Golfer analysiert die Linie am Grün vor dem entscheidenden Putt|putt,linie,gruen,analyse"
  ["golf-putt-einlochen.jpg"]="Der Ball rollt ins Loch – perfekter Putt beim Firmengolf-Event|putt,einlochen,erfolg,freude"
  ["golfer-beim-putten.jpg"]="Golfer beim Putten auf dem gepflegten Grün|golf,putten,gruen,technik"
  ["putting-gruen-uebung.jpg"]="Putting-Übungsgrün für das Training vor dem Event|putting,uebungsgruen,training,vorbereitung"
  ["driving-range-uebung.jpg"]="Golfer übt Abschläge auf der Driving Range vor dem Firmenevent|drivingrange,uebung,abschlag,aufwaermen"
  ["driving-range-golfbaelle.jpg"]="Golfbälle auf der Driving Range – bereit für das Training|drivingrange,baelle,training,range"
  ["golfplatz-rasen-qualitaet.jpg"]="Nahaufnahme des makellosen Rasens eines gepflegten Golfplatzes|golfplatz,rasen,qualitaet,pflege"
  ["bunker-sand-rechen.jpg"]="Bunker-Sand mit Rechen – gepflegter Sandbunker auf dem Golfplatz|bunker,sand,rechen,pflege"
  ["golf-sandbunker.jpg"]="Sandbunker auf dem Golfplatz – strategische Herausforderung|bunker,sand,herausforderung,golfplatz"
  ["tennis-zu-golf-wechsel.jpg"]="Vom Tennis zum Golf – Sport und Teamgeist verbinden|tennis,golf,sport,teamgeist"
  ["anfahrt-oeffentlich.jpg"]="Anfahrt per U-Bahn – optimale Erreichbarkeit des Golfplatzes|anfahrt,ubahn,oeffentlich,erreichbarkeit"
  ["firmengolf-benefit-grafik.png"]="Firmengolf – Play your Benefit. Logo und Claim des Projekts|firmengolf,benefit,logo,claim"
  ["uebungsgruen-putting.jpg"]="Übungsgrün für Putting-Training vor dem Firmengolf-Event|uebungsgruen,putting,training,event"
)

echo ""
echo "── Writing EXIF / IPTC metadata ────────────────────────────"
for FILE in "${!META[@]}"; do
  if [ -f "$DIR/$FILE" ]; then
    IFS='|' read -r DESC KEYWORDS <<< "${META[$FILE]}"
    exiftool -overwrite_original -q \
      -ImageDescription="$DESC" \
      -Caption-Abstract="$DESC" \
      -Title="$FILE" \
      -Keywords="$KEYWORDS" \
      -Subject="$KEYWORDS" \
      -City="München" \
      -State="Bayern" \
      -Country="Deutschland" \
      -Country-PrimaryLocationName="Deutschland" \
      -CopyrightNotice="Firmengolf – firmengolf.de" \
      "$DIR/$FILE"
    echo "  ✓ $FILE"
  fi
done

echo ""
echo "── Done ─────────────────────────────────────────────────────"
ls "$DIR"/*.jpg "$DIR"/*.png 2>/dev/null | sort
