/* eslint-disable */
// Asset helper — all paths root-relative
window.A = (p) => p;
const A = window.A;

// ---------- EVENTS DATA ----------
window.SITE_DATA = {
  formats: [
    { id: 'all',            label: 'Alle Typen' },
    { id: 'teamevent',      label: 'Teamevent' },
    { id: 'afterwork',      label: 'After-Work Golf' },
    { id: 'kundenevent',    label: 'Kundenevent' },
    { id: 'gesundheitstag', label: 'Gesundheitstag' },
    { id: 'offsite',        label: 'Offsite' },
    { id: 'networking',     label: 'Networking' },
    { id: 'andere',         label: 'Andere' },
  ],
  // Formate, die wir nur auf Anfrage planen (siehe Individuelle Events)
  onRequestFormats: [
    'Sommerfest', 'Tagung', 'Firmenjubiläum', 'Kick-off-Veranstaltung',
    'Firmenturnier', 'Incentive', 'Charity-Event', 'Sponsoring-Event', 'CSR-Event',
  ],
  regions: ['Ganz Deutschland', 'Nord', 'Ost', 'Süd', 'West'],

  events: [
    {
      id: 'e1', slug: 'schnupperkurs-hamburg-wendlohe',
      format: 'teamevent', formatLabel: 'Teamevent',
      title: 'Schnupperkurs an einem Nachmittag',
      eyebrow: 'Teamevent · 3 h',
      venue: 'Hamburg-Wendlohe', region: 'Nord',
      duration: '3 h', groupMin: 6, groupMax: 24,
      pricePerPerson: 89,
      rating: 4.9, reviews: 142,
      heroImage: 'assets/imagery/hero-fairway-wide.jpg',
      gallery: ['assets/imagery/event-team.jpg', 'assets/imagery/tile-grass.jpg', 'assets/imagery/event-summer.jpg'],
      tags: ['Einsteigerfreundlich', 'Schläger gestellt', 'PGA-Coach'],
      summary: 'Noch nie einen Schläger gehalten? Gut so — genau dafür ist dieser Nachmittag gedacht. Ein PGA-Pro zeigt euch die ersten Schwünge, ihr probiert Driving Range und Putting Green aus und schließt mit einem Drink auf der Terrasse.',
      includes: ['90 Min. Coaching mit PGA-Pro', 'Komplette Schläger-Leihe', 'Range-Bälle inklusive', 'Putting-Wettbewerb', 'Ein Getränk auf der Terrasse'],
      spotsLeft: 4, featured: true, accent: 'light',
    },
    {
      id: 'e2', slug: 'firmenturnier-koeln-hahnwald',
      format: 'andere', formatLabel: 'Firmenturnier',
      title: 'Das große Firmenturnier',
      eyebrow: 'Firmenturnier · Ganztägig',
      venue: 'Köln-Hahnwald', region: 'West',
      duration: 'Ganztägig', groupMin: 24, groupMax: 96,
      pricePerPerson: 320,
      rating: 4.8, reviews: 31,
      heroImage: 'assets/imagery/event-corporate.jpg',
      gallery: ['assets/imagery/event-toast.jpg', 'assets/imagery/venue-clubhouse.jpg'],
      tags: ['Pokal & Preise', 'Catering inklusive', 'Fotograf', 'Shotgun-Start'],
      summary: 'Ein klassisches 18-Loch-Turnier mit Shotgun-Start, Fotograf vor Ort, Mittagspause im Clubhaus und einer Siegerehrung bei Sonnenuntergang. Wir kümmern uns um Scoring, Caddies und die Trophäen — du bist nur Gastgeber.',
      includes: ['Shotgun-Start 9:00 Uhr', 'Live-Scoring & Leaderboard', 'Mittagessen im Clubhaus', 'Siegerehrung mit Sektempfang', 'Trophäen & Sachpreise'],
      spotsLeft: 28, featured: true, accent: 'dark',
    },
    {
      id: 'e3', slug: 'team-building-muenchen-riem',
      format: 'teamevent', formatLabel: 'Teamevent',
      title: 'Team-Building auf dem Übungsgrün',
      eyebrow: 'Teamevent · Halbtägig',
      venue: 'München-Riem', region: 'Süd',
      duration: '5 h', groupMin: 8, groupMax: 32,
      pricePerPerson: 165,
      rating: 4.9, reviews: 67,
      heroImage: 'assets/imagery/event-team.jpg',
      gallery: ['assets/imagery/tile-people.jpg', 'assets/imagery/event-summer-2.jpg'],
      tags: ['Mixed-Teams', 'Coach', 'Mittagessen'],
      summary: 'Gemischte Zweier-Teams, eine kleine Einführung, dann ein 9-Loch-Scramble bei dem Können nicht zählt — sondern Zusammenspiel. Endet mit Mittagessen draußen.',
      includes: ['Team-Briefing & Aufwärmen', 'Coach pro Vierergruppe', '9-Loch Scramble', 'Mittagessen draußen', 'Team-Foto'],
      spotsLeft: 6, accent: 'light',
    },
    {
      id: 'e4', slug: 'networking-runde-berlin-wannsee',
      format: 'networking', formatLabel: 'Networking',
      title: 'Networking-Runde am Wannsee',
      eyebrow: 'Networking · 4 h',
      venue: 'Berlin-Wannsee', region: 'Ost',
      duration: '4 h (Nachmittag)', groupMin: 8, groupMax: 20,
      pricePerPerson: 195,
      rating: 4.7, reviews: 28,
      heroImage: 'assets/imagery/hero-meadow.jpg',
      gallery: ['assets/imagery/event-toast.jpg', 'assets/imagery/venue-meadow.jpg'],
      tags: ['Mixed Level', 'Aperitif', 'Diskret'],
      summary: 'Eine kleine, gemischte Runde — eure Kunden, eure Partner, drei Mitarbeitende. Niedrigschwellige 9 Loch ohne Druck, anschließend ein Aperitif auf der Terrasse mit Blick über den See.',
      includes: ['9 Loch in Vierergruppen', 'Begrüßung mit Coach', 'Aperitif auf der Terrasse', 'Diskreter Concierge vor Ort'],
      spotsLeft: 3, accent: 'light',
    },
    {
      id: 'e5', slug: 'incentive-suedtirol',
      format: 'offsite', formatLabel: 'Offsite',
      title: 'Incentive-Reise Südtirol',
      eyebrow: 'Offsite · 3 Tage',
      venue: 'Petersberg, Südtirol', region: 'Süd',
      duration: '3 Tage / 2 Nächte', groupMin: 8, groupMax: 24,
      pricePerPerson: 1480,
      rating: 4.9, reviews: 14,
      heroImage: 'assets/imagery/hero-mountains.jpg',
      gallery: ['assets/imagery/venue-clubhouse.jpg', 'assets/imagery/event-clubhouse-2.jpg', 'assets/imagery/tile-trail.jpg'],
      tags: ['Übernachtung', 'Bergpanorama', 'Private Dinings'],
      summary: 'Drei Tage in den Dolomiten — vormittags 18 Loch mit Bergblick, nachmittags Wandern oder Wellness, abends private Dinings im Weinkeller. Für Vertriebs-Top-Performer oder Strategie-Team.',
      includes: ['2 Nächte 4-Sterne-Hotel', '2× 18 Loch mit Caddie', 'Private Dinings', 'Wandern oder Wellness', 'Transfer ab Flughafen'],
      spotsLeft: 2, featured: true, accent: 'dark',
    },
    {
      id: 'e6', slug: 'coaching-stunden-stuttgart',
      format: 'afterwork', formatLabel: 'After-Work Golf',
      title: 'Trainerstunde nach Maß',
      eyebrow: 'After-Work Golf · 60 oder 90 Min.',
      venue: 'Stuttgart-Solitude', region: 'Süd',
      duration: '60–90 Min.', groupMin: 1, groupMax: 8,
      pricePerPerson: 75,
      rating: 4.9, reviews: 203,
      heroImage: 'assets/imagery/tile-grass.jpg',
      gallery: ['assets/imagery/event-summer.jpg'],
      tags: ['Einzelcoaching', 'Kleingruppe', 'Buchbar nach Bedarf'],
      summary: 'Für alle, die regelmäßig dranbleiben wollen — Einzel- oder Kleingruppen-Coaching mit einem PGA-Pro. Buchbar als Einzelstunde oder als 5er-Karte für Vielnutzer.',
      includes: ['Einzel- oder Kleingruppe (max. 8)', 'Schwung-Video & Analyse', 'Range-Bälle inklusive', '5er-Karte verfügbar'],
      spotsLeft: 18, accent: 'light',
    },
    {
      id: 'e7', slug: 'gesundheitstag-frankfurt',
      format: 'gesundheitstag', formatLabel: 'Gesundheitstag',
      title: 'Bewegung statt PowerPoint',
      eyebrow: 'Gesundheitstag · 6 h',
      venue: 'Frankfurt-Niederrad', region: 'West',
      duration: '6 h', groupMin: 15, groupMax: 60,
      pricePerPerson: 145,
      rating: 4.8, reviews: 41,
      heroImage: 'assets/imagery/hero-forest.jpg',
      gallery: ['assets/imagery/tile-trail.jpg', 'assets/imagery/event-team.jpg'],
      tags: ['Bewegung', 'Mental Health', 'Healthy Lunch'],
      summary: 'Ein Gesundheitstag im Grünen — geführter Spaziergang über den Platz, Einsteiger-Coaching auf der Range, Mobility-Session mit Physiotherapeut und ein gesundes Mittagessen. Steuerfrei als BGM-Maßnahme abrechenbar.',
      includes: ['Geführter Platz-Spaziergang', 'Einsteiger-Coaching auf Range', 'Mobility-Session mit Physio', 'Healthy Lunch', 'BGM-konforme Abrechnung'],
      spotsLeft: 10, accent: 'light',
    },
    {
      id: 'e8', slug: 'strategie-offsite-luedersburg',
      format: 'offsite', formatLabel: 'Offsite',
      title: 'Strategie-Offsite Schloss Lüdersburg',
      eyebrow: 'Offsite · 2 Tage',
      venue: 'Schloss Lüdersburg', region: 'Nord',
      duration: '2 Tage, 1 Nacht', groupMin: 10, groupMax: 24,
      pricePerPerson: 540,
      rating: 4.9, reviews: 22,
      heroImage: 'assets/imagery/venue-clubhouse.jpg',
      gallery: ['assets/imagery/event-corporate.jpg', 'assets/imagery/hero-meadow.jpg'],
      tags: ['Meeting-Räume', 'Übernachtung', 'Private Dinings'],
      summary: 'Vormittags Workshop im Schloss, nachmittags 9 Loch im Wald. Zwei Breakout-Räume, privates Dinner und Übernachtung im Schloss-Hotel. Perfekt für Strategie-Sessions, die mehr brauchen als ein Hotel-Konferenzraum.',
      includes: ['Zwei Breakout-Räume', 'Privates Dinner', '9 Loch Nachmittagsrunde', 'Übernachtung im Schloss', 'Fahrräder & Wanderwege'],
      spotsLeft: 4, accent: 'light',
    },
    {
      id: 'e9', slug: 'kundenevent-tasting-stuttgart',
      format: 'kundenevent', formatLabel: 'Kundenevent',
      title: 'Tasting-Abend auf der Terrasse',
      eyebrow: 'Kundenevent · 4 h',
      venue: 'Stuttgart-Solitude', region: 'Süd',
      duration: '4 h', groupMin: 12, groupMax: 40,
      pricePerPerson: 220,
      rating: 4.9, reviews: 36,
      heroImage: 'assets/imagery/event-clubhouse-2.jpg',
      gallery: ['assets/imagery/event-toast.jpg', 'assets/imagery/event-corporate.jpg'],
      tags: ['Sommelier', 'Catering', 'Indoor-Backup'],
      summary: 'Ein Sommelier-geführtes Tasting kombiniert mit einem kurzen Putting-Wettbewerb auf dem Übungsgrün. Endet mit Dinner auf der Terrasse, wenn die Sonne untergeht.',
      includes: ['Sommelier-Tasting (6 Weine)', 'Putting-Wettbewerb', 'Dinner auf der Terrasse', 'Indoor-Backup'],
      spotsLeft: 11, accent: 'light',
    },
    {
      id: 'e10', slug: 'sommerfest-licht-aus-muenchen',
      format: 'andere', formatLabel: 'Sommerfest',
      title: 'Sommerfest unter Flutlicht',
      eyebrow: 'Sommerfest · Abend',
      venue: 'GC München West', region: 'Süd',
      duration: 'Abend (6 h)', groupMin: 30, groupMax: 80,
      pricePerGroup: 2400,
      rating: 4.8, reviews: 19,
      heroImage: 'assets/imagery/venue-meadow.jpg',
      gallery: ['assets/imagery/event-summer-2.jpg', 'assets/imagery/event-toast.jpg'],
      tags: ['Flutlicht', 'Food Trucks', 'DJ', 'Indoor-Backup'],
      summary: 'Putten unter Flutlicht, Food Trucks auf dem Übungsgrün, DJ auf der Terrasse — und ein Indoor-Backup falls das Wetter umschlägt.',
      includes: ['Flutlicht-Putting', 'Food Trucks + Bar', 'DJ bis 23:00', 'Indoor-Backup'],
      spotsLeft: 9, accent: 'dark',
    },
    {
      id: 'e11', slug: 'first-swings-after-work-berlin',
      format: 'afterwork', formatLabel: 'After-Work Golf',
      title: 'First Swings — nach Feierabend',
      eyebrow: 'After-Work Golf · 2 h',
      venue: 'Berlin-Wannsee', region: 'Ost',
      duration: '2 h', groupMin: 4, groupMax: 12,
      pricePerPerson: 79,
      rating: 4.7, reviews: 89,
      heroImage: 'assets/imagery/event-summer.jpg',
      gallery: ['assets/imagery/tile-grass.jpg'],
      tags: ['Einsteigerfreundlich', 'After-Work', 'Range'],
      summary: 'Zwei Stunden nach Feierabend auf der Range. PGA-Coach, Schläger gestellt, Range-Bälle inklusive. Mehr braucht ein erster Schwung nicht.',
      includes: ['PGA-Coach', 'Komplette Ausrüstung', 'Range-Bälle'],
      spotsLeft: 8, accent: 'light',
    },
    {
      id: 'e12', slug: 'kundenevent-charity-koeln',
      format: 'kundenevent', formatLabel: 'Kundenevent',
      title: 'Charity-Cup mit Kunden',
      eyebrow: 'Kundenevent · Ganztägig',
      venue: 'Köln-Refrath', region: 'West',
      duration: 'Ganztägig', groupMin: 16, groupMax: 48,
      pricePerPerson: 380,
      rating: 4.9, reviews: 17,
      heroImage: 'assets/imagery/event-corporate.jpg',
      gallery: ['assets/imagery/event-team.jpg', 'assets/imagery/venue-clubhouse.jpg'],
      tags: ['Charity-Spendentopf', 'Auktion', 'Catering'],
      summary: 'Eure Kunden, ihre Partner — 18 Loch in Vierer-Flights mit einem Spendentopf pro Loch. Schluss mit Auktion und Übergabe an euren Spendenpartner.',
      includes: ['18 Loch in Vierer-Flights', 'Spendentopf pro Loch', 'Stille Auktion', 'Catering & Aperitif', 'Spendenscheck-Übergabe'],
      spotsLeft: 5, accent: 'light',
    },

    // ---- GC München West — gepflegt im Partner-Portal, hier öffentlich gelistet ----
    {
      id: 'e13', slug: 'schnupperkurs-muenchen-west',
      format: 'teamevent', formatLabel: 'Schnupperkurs',
      title: 'Erster Schwung — Schnupperkurs für Teams',
      eyebrow: 'Schnupperkurs · 3 h',
      venue: 'GC München West', region: 'Süd',
      duration: '3 h', groupMin: 6, groupMax: 24,
      pricePerPerson: 89,
      rating: 4.8, reviews: 47,
      heroImage: 'assets/imagery/hero-fairway-wide.jpg',
      gallery: ['assets/imagery/event-team.jpg', 'assets/imagery/tile-grass.jpg'],
      tags: ['Einsteigerfreundlich', 'Schläger gestellt', 'PGA-Pro'],
      summary: '3 Stunden auf der Range mit unseren Pros — Schläger, Bälle und gute Laune inklusive. Ideal für Teams, die zum ersten Mal abschlagen.',
      includes: ['Coaching mit PGA-Pro', 'Komplette Schläger-Leihe', 'Range-Bälle', 'Putting-Wettbewerb', 'Getränk auf der Terrasse'],
      spotsLeft: 6, accent: 'light',
    },
    {
      id: 'e14', slug: 'firmen-cup-muenchen-west',
      format: 'andere', formatLabel: 'Firmenturnier',
      title: '18-Loch Firmen-Cup',
      eyebrow: 'Firmenturnier · Ganztägig',
      venue: 'GC München West', region: 'Süd',
      duration: 'Ganztägig', groupMin: 24, groupMax: 80,
      pricePerPerson: 145,
      rating: 4.9, reviews: 31,
      heroImage: 'assets/imagery/event-corporate.jpg',
      gallery: ['assets/imagery/event-toast.jpg', 'assets/imagery/venue-clubhouse.jpg'],
      tags: ['Stableford', 'Startergeschenk', 'Siegerehrung'],
      summary: 'Klassisches Stableford-Turnier mit Startergeschenk, Halfway-Verpflegung und Siegerehrung auf der Terrasse. Wir kümmern uns um Scoring und Trophäen.',
      includes: ['Shotgun-Start', 'Live-Scoring', 'Halfway-Verpflegung', 'Siegerehrung', 'Trophäen & Preise'],
      spotsLeft: 22, accent: 'light',
    },
    {
      id: 'e15', slug: 'teamevent-muenchen-west',
      format: 'teamevent', formatLabel: 'Teamevent',
      title: 'Team auf dem Platz',
      eyebrow: 'Teamevent · Halbtägig',
      venue: 'GC München West', region: 'Süd',
      duration: '5 h', groupMin: 8, groupMax: 40,
      pricePerPerson: 119,
      rating: 4.8, reviews: 38,
      heroImage: 'assets/imagery/event-team.jpg',
      gallery: ['assets/imagery/tile-people.jpg', 'assets/imagery/event-summer-2.jpg'],
      tags: ['Mixed-Teams', 'Coaching', 'Lunch'],
      summary: 'Halbtägig: Coaching, Mini-Wettkampf und gemeinsames Lunch auf der Terrasse. Können zählt nicht — Zusammenspiel schon.',
      includes: ['Team-Briefing', 'Coaching in Kleingruppen', 'Mini-Wettkampf', 'Lunch auf der Terrasse', 'Team-Foto'],
      spotsLeft: 8, accent: 'light',
    },
    {
      id: 'e16', slug: 'tagung-und-tee-muenchen-west',
      format: 'offsite', formatLabel: 'Offsite',
      title: 'Tagung & Tee',
      eyebrow: 'Offsite · Ganztägig',
      venue: 'GC München West', region: 'Süd',
      duration: 'Ganztägig', groupMin: 12, groupMax: 30,
      pricePerPerson: 189,
      rating: 4.8, reviews: 16,
      heroImage: 'assets/imagery/venue-clubhouse.jpg',
      gallery: ['assets/imagery/event-corporate.jpg', 'assets/imagery/hero-meadow.jpg'],
      tags: ['Tagungsraum', 'Schnupperrunde', 'Abendessen'],
      summary: 'Tagungsraum bis 30 Personen am Vormittag, anschließend Schnupperrunde auf dem Platz und gemeinsames Abendessen.',
      includes: ['Tagungsraum mit Technik', 'Mittagsimbiss', 'Schnupperrunde mit Pro', 'Gemeinsames Abendessen'],
      spotsLeft: 5, accent: 'light',
    },
    {
      id: 'e17', slug: 'pro-stunde-muenchen-west',
      format: 'afterwork', formatLabel: 'Coaching',
      title: 'Pro-Stunde mit Markus',
      eyebrow: 'Coaching · 60 Min.',
      venue: 'GC München West', region: 'Süd',
      duration: '60 Min.', groupMin: 1, groupMax: 2,
      pricePerPerson: 75,
      rating: 4.9, reviews: 64,
      heroImage: 'assets/imagery/tile-grass.jpg',
      gallery: ['assets/imagery/event-summer.jpg'],
      tags: ['Einzelcoaching', 'Videoanalyse', 'Nach Bedarf'],
      summary: 'Einzel- oder 2er-Coaching auf der Range mit unserem Head-Pro Markus. Videoanalyse auf Wunsch — buchbar nach Bedarf.',
      includes: ['60 Min. mit Head-Pro', 'Schwung-Videoanalyse', 'Range-Bälle inklusive'],
      spotsLeft: 12, accent: 'light',
    },
  ],

  // ---------- BLOG ----------
  posts: [
    {
      slug: 'golf-als-corporate-benefit',
      title: 'Warum Golf zum Corporate Benefit passt — und wie der steuerfreie Sachbezug funktioniert',
      excerpt: '50 € pro Monat steuerfrei, fittere Mitarbeitende und ein Benefit, der Generationen verbindet. Wir erklären die wichtigsten Punkte.',
      author: 'Lena Hoffmann',
      role: 'People Lead',
      date: '14. Mai 2026',
      readTime: '6 Min.',
      tag: 'Benefits',
      image: 'assets/imagery/event-team.jpg',
      featured: true,
    },
    {
      slug: 'event-checkliste',
      title: 'Die 12-Punkte-Checkliste für dein erstes Firmen-Golfevent',
      excerpt: 'Vom richtigen Zeitfenster bis zum Wetter-Backup — was du im Blick haben solltest, bevor du ein Event buchst.',
      author: 'Jonas Bredow',
      role: 'Head of Events',
      date: '2. Mai 2026',
      readTime: '4 Min.',
      tag: 'Praxis',
      image: 'assets/imagery/event-corporate.jpg',
    },
    {
      slug: 'einsteiger-mythos',
      title: '"Aber wir können doch alle nicht Golf spielen" — der größte Einsteiger-Mythos',
      excerpt: 'Genau das ist der Punkt. Wir zeigen, wie ein Schnupperkurs für absolute Einsteigende funktioniert.',
      author: 'Petra Sailer',
      role: 'PGA-Coach',
      date: '18. April 2026',
      readTime: '5 Min.',
      tag: 'Einsteiger',
      image: 'assets/imagery/tile-grass.jpg',
    },
    {
      slug: 'sommerfest-2026',
      title: 'Sommerfest 2026: drei Formate, die nicht nach Kantine schmecken',
      excerpt: 'Vom Flutlicht-Putting bis zum Food-Truck auf der Range — Ideen, die euren Sommer in Erinnerung bleiben lassen.',
      author: 'Jonas Bredow',
      role: 'Head of Events',
      date: '5. April 2026',
      readTime: '7 Min.',
      tag: 'Inspiration',
      image: 'assets/imagery/event-summer-2.jpg',
    },
    {
      slug: 'wieso-offsite-im-gruenen',
      title: 'Wieso Strategie-Offsites im Grünen besser laufen',
      excerpt: 'Bewegung an frischer Luft, weniger Bildschirm, mehr Konzentration. Was die Forschung dazu sagt — und was unsere Kunden berichten.',
      author: 'Dr. Carla Meyn',
      role: 'Gast-Autorin',
      date: '21. März 2026',
      readTime: '8 Min.',
      tag: 'Research',
      image: 'assets/imagery/hero-forest.jpg',
    },
    {
      slug: 'nachhaltiger-platzbetrieb',
      title: 'Wie nachhaltig ist ein moderner Golfplatz wirklich?',
      excerpt: 'Wasser, Mahd, Biodiversität — wir haben mit drei Greenkeepern gesprochen, was sich in den letzten zehn Jahren verändert hat.',
      author: 'Lena Hoffmann',
      role: 'People Lead',
      date: '8. März 2026',
      readTime: '9 Min.',
      tag: 'Nachhaltigkeit',
      image: 'assets/imagery/hero-meadow.jpg',
    },
  ],

  // ---------- PARTNERS ----------
  partners: ['Quartz Labs', 'North Studio', 'Hartmann GmbH', 'Steinblick', 'Halde & Co.', 'Werkstatt 4', 'Bauer & Söhne', 'Pixelhof'],

  steps: [
    { n: '01', title: 'Du sagst uns, was du planst.',  body: 'Anlass, Gruppe, Zeitraum. Eine Anfrage — mehr brauchen wir nicht.' },
    { n: '02', title: 'Wir kuratieren passende Plätze.', body: 'Innerhalb von 24 Stunden bekommst du zwei bis drei Optionen mit Format, Preis und Verfügbarkeit.' },
    { n: '03', title: 'Du wählst, wir koordinieren.',  body: 'Ein Ansprechpartner, eine Rechnung. Der Platz organisiert vor Ort — du bist nur Gastgeberin.' },
  ],

  testimonials: [
    {
      quote: 'Das Team kam aufgeladen zurück, und drei Leute haben am Sonntag direkt wieder gespielt. Die Latte für nächstes Jahr liegt hoch.',
      name: 'Lena Hoffmann', role: 'People Lead · Quartz Labs', photo: 'assets/imagery/avatar-1.jpg',
    },
    {
      quote: 'Wir hatten eine Sales-Offsite mit 22 Leuten gebucht. Ein Ansprechpartner, eine Rechnung — danach war ich überzeugt.',
      name: 'Matthias Reuter', role: 'VP Sales · Hartmann GmbH', photo: 'assets/imagery/avatar-2.jpg',
    },
    {
      quote: 'Unser Gesundheitstag war zum dritten Mal in Folge mit Firmengolf. Buchung im Self-Service, BGM-konform, fertig.',
      name: 'Sandra Klein', role: 'HR-Direktorin · Werkstatt 4', photo: 'assets/imagery/avatar-3.jpg',
    },
  ],

  team: [
    { name: 'Lena Hoffmann',  role: 'CEO & Co-Founderin',  photo: 'assets/imagery/avatar-1.jpg', bio: 'Davor 8 Jahre HR-Strategie bei Otto Group. Spielt Handicap 18, beweist täglich, dass das reicht.' },
    { name: 'Jonas Bredow',   role: 'Head of Events',      photo: 'assets/imagery/avatar-2.jpg', bio: 'Hat 12 Jahre Hochzeiten und Firmenfeste produziert, bevor er den Schläger entdeckt hat.' },
    { name: 'Petra Sailer',   role: 'Coaching-Lead, PGA',  photo: 'assets/imagery/avatar-3.jpg', bio: 'PGA-zertifiziert. Unterrichtet absolute Einsteigende — und genießt jede Sekunde davon.' },
    { name: 'Marek Wojcik',   role: 'Head of Partnerships', photo: 'assets/imagery/avatar-4.jpg', bio: 'Spricht mit Greenkeepern, Clubmanagern und Pros. Findet immer einen freien Slot.' },
    { name: 'Annika Reuß',    role: 'Product & Engineering', photo: 'assets/imagery/avatar-5.jpg', bio: 'Baut die Software, die das Ganze still im Hintergrund funktionieren lässt.' },
    { name: 'Tom Krüger',     role: 'Customer Success',     photo: 'assets/imagery/avatar-1.jpg', bio: 'Dein erster Ansprechpartner, bevor und nachdem du bei uns gebucht hast.' },
  ],

  numbers: [
    { v: '180+',  l: 'Partnerplätze in Deutschland' },
    { v: '2.400', l: 'Mitarbeitende im Benefit-Programm' },
    { v: '< 24 h', l: 'Antwortzeit auf jede Anfrage' },
    { v: '4,9 ★', l: 'Durchschnittliche Bewertung' },
  ],
};

// ---------- VENUES (Golfplätze) ----------
// One record per partner course. `venue` matches the string used on events,
// so events are grouped by it. lat/lng drive the map projection.
window.SITE_DATA.venues = [
  { slug: 'hamburg-wendlohe', venue: 'Hamburg-Wendlohe', name: 'Golf-Club Hamburg-Wendlohe', city: 'Hamburg', region: 'Nord',
    holes: 27, par: 72, lat: 53.63, lng: 9.95, image: 'assets/imagery/hero-fairway-wide.jpg',
    blurb: 'Drei abwechslungsreiche Neun-Loch-Schleifen im Hamburger Norden — stadtnah, gut erreichbar und ideal für den ersten Schwung mit dem Team.',
    address: 'Tangstedter Landstraße 360, 22417 Hamburg' },
  { slug: 'koeln-hahnwald', venue: 'Köln-Hahnwald', name: 'Golf- & Land-Club Köln', city: 'Köln', region: 'West',
    holes: 18, par: 72, lat: 50.87, lng: 6.97, image: 'assets/imagery/venue-clubhouse.jpg',
    blurb: 'Traditionsreicher 18-Loch-Parklandkurs im Süden Kölns. Großzügige Fairways, alter Baumbestand und eine Terrasse für den Ausklang.',
    address: 'Golfplatz 2, 50996 Köln' },
  { slug: 'muenchen-riem', venue: 'München-Riem', name: 'Golfpark München-Riem', city: 'München', region: 'Süd',
    holes: 18, par: 71, lat: 48.13, lng: 11.69, image: 'assets/imagery/venue-meadow.jpg',
    blurb: 'Weitläufige Anlage im Münchner Osten mit großer Übungsanlage — perfekt für Teamevents und Schnupperrunden.',
    address: 'Grasweg 4, 81829 München' },
  { slug: 'berlin-wannsee', venue: 'Berlin-Wannsee', name: 'Golf- und Land-Club Wannsee', city: 'Berlin', region: 'Ost',
    holes: 18, par: 71, lat: 52.42, lng: 13.16, image: 'assets/imagery/golf-island.jpg',
    blurb: 'Idyllisch am Wasser gelegen, nur 20 Minuten vom Zentrum. Diskret, ruhig und ideal für Kunden- und Networking-Runden.',
    address: 'Golfweg 22, 14109 Berlin' },
  { slug: 'stuttgart-solitude', venue: 'Stuttgart-Solitude', name: 'Golfclub Stuttgart Solitude', city: 'Stuttgart', region: 'Süd',
    holes: 18, par: 72, lat: 48.79, lng: 9.10, image: 'assets/imagery/golf-approach.jpg',
    blurb: 'Anspruchsvoller Kurs vor den Toren Stuttgarts mit erstklassiger Trainingsanlage und einem der besten Pros der Region.',
    address: 'Am Golfplatz 1, 71229 Leonberg' },
  { slug: 'frankfurt-niederrad', venue: 'Frankfurt-Niederrad', name: 'Frankfurter Golf Club', city: 'Frankfurt', region: 'West',
    holes: 18, par: 71, lat: 50.08, lng: 8.63, image: 'assets/imagery/tile-trail.jpg',
    blurb: 'Der älteste Club Frankfurts, direkt am Stadtwald. Schnell erreichbar aus dem Bankenviertel — ideal für Gesundheitstage.',
    address: 'Golfstraße 41, 60528 Frankfurt am Main' },
  { slug: 'schloss-luedersburg', venue: 'Schloss Lüdersburg', name: 'Schloss Lüdersburg', city: 'Lüneburg', region: 'Nord',
    holes: 36, par: 73, lat: 53.30, lng: 10.58, image: 'assets/imagery/hero-meadow.jpg',
    blurb: 'Golfresort mit 36 Loch, Schlosshotel und Restaurant — die erste Adresse für mehrtägige Offsites und Incentives im Norden.',
    address: 'Lüdersburger Straße 21, 21379 Lüdersburg' },
  { slug: 'koeln-refrath', venue: 'Köln-Refrath', name: 'Golfclub Köln-Refrath', city: 'Bergisch Gladbach', region: 'West',
    holes: 18, par: 72, lat: 50.95, lng: 7.08, image: 'assets/imagery/event-corporate.jpg',
    blurb: 'Bekannt für gepflegte Grüns und ein engagiertes Eventteam — gerne gebucht für Charity-Cups und Firmenturniere.',
    address: 'Steinacher Weg 1, 51427 Bergisch Gladbach' },
  { slug: 'gc-muenchen-west', venue: 'GC München West', name: 'GC München West', city: 'München', region: 'Süd',
    holes: 18, par: 72, lat: 48.15, lng: 11.45, image: 'assets/imagery/golf-green-flag.jpg',
    blurb: 'Unser aktivster Partnerplatz im Münchner Westen — vom Schnupperkurs bis zum Sommerfest unter Flutlicht ist hier alles möglich.',
    address: 'Münchner Straße 57, 82152 Krailling' },
  { slug: 'petersberg-suedtirol', venue: 'Petersberg, Südtirol', name: 'Golfclub Petersberg', city: 'Südtirol', region: 'Süd',
    holes: 18, par: 71, lat: 46.36, lng: 11.46, image: 'assets/imagery/hero-mountains.jpg',
    blurb: 'Unser Incentive-Platz in den Dolomiten — Bergpanorama, mildes Klima und ein Resort, das mehrtägige Reisen unvergesslich macht.',
    address: 'Pidol 15, 39040 Petersberg, Italien' },
];

window.SITE_DATA.eventsForVenue = function (venueName) {
  return window.SITE_DATA.events.filter(function (e) { return e.venue === venueName; });
};
