<?php
/**
 * Kontaktmails für Stammdaten-Plätze, generiert am 28.09.2026 aus
 * docs/golfplaetze-bayern-emails.tsv (Verzeichnis-id → Mail) und
 * docs/simulatoren-ansprache-2026-09.csv (Schlüssel Name|PLZ → Mail, Telefon, Website).
 * Nur Sammeladressen der Anlagen, keine Personen, keine Bewertungen. Datei nicht von Hand
 * pflegen, sondern neu generieren (Skript im Session-Scratchpad, Muster in docs/prozess-anfrage-bis-rechnung.md).
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/** @return array<int,array{name:string,plz:string,email:string}> Verzeichnis-id => Kontakt */
function fge_stammdaten_mails_courses(): array {
	return [
		1 => [ 'name' => '1. Golf Club Fürth e.V.', 'plz' => '90768', 'email' => 'info@golfclub-fuerth.de' ],
		7 => [ 'name' => 'Allgäuer Golf- und Landclub e.V.', 'plz' => '87724', 'email' => 'info@aglc.de' ],
		8 => [ 'name' => 'Altmühlgolf Beilngries GmbH', 'plz' => '92339', 'email' => 'info@altmuehlgolf.de' ],
		20 => [ 'name' => 'Bavaria Golf Anthal', 'plz' => '', 'email' => 'info@golf-anthal.de' ],
		21 => [ 'name' => 'Bavarian Golfclub München-Eicherloh e.V.', 'plz' => '85464', 'email' => 'info@bavariangc.de' ],
		22 => [ 'name' => 'Bella Vista Golfpark Bad Birnbach', 'plz' => '84364', 'email' => 'kurverwaltung@badbirnbach.de' ],
		32 => [ 'name' => 'Chiemsee Golf-Club Prien e.V.', 'plz' => '83209', 'email' => 'info@cgc-prien.de' ],
		35 => [ 'name' => 'Das Achental', 'plz' => '83224', 'email' => 'info@das-achental.com' ],
		36 => [ 'name' => 'Deggendorfer Golfclub e.V.', 'plz' => '94571', 'email' => 'info@deggendorfer-golfclub.de' ],
		37 => [ 'name' => 'Der Golf Club am Obinger See', 'plz' => '83119', 'email' => 'dergolfclub@t-online.de' ],
		66 => [ 'name' => 'Golf & Yachtclub Gut Minoritenhof', 'plz' => '93161', 'email' => 'welcome@golfsinzing.de' ],
		69 => [ 'name' => 'Golf Club am Eixendorfer See', 'plz' => '92444', 'email' => 'info@golf-eixendorfer-see.de' ],
		70 => [ 'name' => 'Golf Club Am Habsberg e.V.', 'plz' => '92355', 'email' => 'info@juragolf.de' ],
		73 => [ 'name' => 'Golf Club Berchtesgadener Land e.V.', 'plz' => '83404', 'email' => 'info@gcbgl.de' ],
		75 => [ 'name' => 'Golf Club Dachau e.V.', 'plz' => '85221', 'email' => 'info@gcdachau.de' ],
		77 => [ 'name' => 'Golf Club Ebersberg e.V.', 'plz' => '85643', 'email' => 'info@gc-ebersberg.de' ],
		83 => [ 'name' => 'Golf Club Gersthofen e.V.', 'plz' => '86169', 'email' => 'info@golfclub-gersthofen.de' ],
		85 => [ 'name' => 'Golf Club Gut Ising e.V.', 'plz' => '83339', 'email' => 'hotel@gut-ising.de' ],
		92 => [ 'name' => 'Golf Club Hohenpähl e.V.', 'plz' => '82396', 'email' => 'info@gchp.de' ],
		96 => [ 'name' => 'Golf Club Kitzingen e.V.', 'plz' => '97318', 'email' => 'info@golfclub-kitzingen.de' ],
		107 => [ 'name' => 'Golf Club Schloß Klingenburg e.V.', 'plz' => '89343', 'email' => 'info@golf-klingenburg.de' ],
		109 => [ 'name' => 'Golf Club Schweinfurt e.V.', 'plz' => '97453', 'email' => 'info@golfclub-schweinfurt.de' ],
		125 => [ 'name' => 'Golf Club Würzburg e.V.', 'plz' => '97084', 'email' => 'info@golfclub-wuerzburg.de' ],
		137 => [ 'name' => 'Golf Resort Anetseder', 'plz' => '94136', 'email' => 'info@golf-passau.de' ],
		144 => [ 'name' => 'Golf- &  Landclub Karwendel e.V.', 'plz' => '82499', 'email' => 'info@golfclub-karwendel.de' ],
		150 => [ 'name' => 'Golf- und Land-Club Regensburg e.V.', 'plz' => '93093', 'email' => 'sekretariat@golfclub-regensburg.de' ],
		160 => [ 'name' => 'Golf- und Landclub Oberpfälzer Wald e.V.', 'plz' => '92431', 'email' => 'info@golf-oberpfalz.de' ],
		162 => [ 'name' => 'Golf- und Landclub Schmidmühlen e.V.', 'plz' => '92287', 'email' => 'golf@glcs.bayern' ],
		173 => [ 'name' => 'Golf-Club Bad Kissingen e.V.', 'plz' => '97688', 'email' => 'info@golfclubbadkissingen.de' ],
		178 => [ 'name' => 'Golf-Club Bayreuth e.V.', 'plz' => '95448', 'email' => 'info@gc-bayreuth.de' ],
		185 => [ 'name' => 'Golf-Club Coburg e.V. Schloss Tambach', 'plz' => '96479', 'email' => 'info@gc-coburg.de' ],
		188 => [ 'name' => 'Golf-Club Feldafing e.V.', 'plz' => '82340', 'email' => 'info@golfclub-feldafing.de' ],
		190 => [ 'name' => 'Golf-Club Furth im Wald e.V.', 'plz' => '93437', 'email' => 'info@gc-furth.de' ],
		199 => [ 'name' => 'Golf-Club Herzogenaurach e.V.', 'plz' => '91074', 'email' => 'info@golfclub-herzogenaurach.de' ],
		204 => [ 'name' => 'Golf-Club Höslwang im Chiemgau e.V.', 'plz' => '83129', 'email' => 'info@golfclub-hoeslwang.de' ],
		205 => [ 'name' => 'Golf-Club Ingolstadt e.V.', 'plz' => '85049', 'email' => 'info@golf-ingolstadt.de' ],
		210 => [ 'name' => 'Golf-Club Kronach e.V.', 'plz' => '96328', 'email' => 'info@gc-kronach.de' ],
		213 => [ 'name' => 'Golf-Club Lindau-Bad Schachen e.V.', 'plz' => '88131', 'email' => 'info@golfclub-lindau.de' ],
		218 => [ 'name' => 'Golf-Club Neumarkt e.V.', 'plz' => '', 'email' => 'club@golfclub-neumarkt.de' ],
		221 => [ 'name' => 'Golf-Club Oberfranken e.V.', 'plz' => '95349', 'email' => 'info@gc-oberfranken.de' ],
		227 => [ 'name' => 'Golf-Club Schloss Elkofen e.V.', 'plz' => '85567', 'email' => 'info@gcschlosselkofen.de' ],
		233 => [ 'name' => 'Golf-Club Straubing Stadt und  Land e.V.', 'plz' => '94356', 'email' => 'info@golfclub-straubing.de' ],
		236 => [ 'name' => 'Golf-Club Tutzing e.V.', 'plz' => '82327', 'email' => 'info@golfclub-tutzing.de' ],
		247 => [ 'name' => 'Golf-Resort Bad Griesbach e.V.', 'plz' => '94086', 'email' => 'info@quellness-golf.com' ],
		250 => [ 'name' => 'Golfanlage Alpenseehof', 'plz' => '87484', 'email' => 'info@alpenseehof.de' ],
		251 => [ 'name' => 'Golfanlage Gerhelm', 'plz' => '91235', 'email' => 'buero@gerhelm.de' ],
		254 => [ 'name' => 'Golfanlage Gut Leimershof', 'plz' => '96149', 'email' => 'info@leimershof-golfanlage.de' ],
		257 => [ 'name' => 'Golfanlage Harthausen', 'plz' => '85630', 'email' => 'info@golfanlage-harthausen.de' ],
		265 => [ 'name' => 'Golfanlage Puschendorf', 'plz' => '', 'email' => 'buero@golfanlage-puschendorf.de' ],
		272 => [ 'name' => 'Golfanlage Weiherhof', 'plz' => '86459', 'email' => 'golfanlageweiherhof@yahoo.de' ],
		273 => [ 'name' => 'Golfanlagen Erlangen Besitz GmbH & Co. KG', 'plz' => '90542', 'email' => 'info@gc-erlangen.de' ],
		275 => [ 'name' => 'Golfclub Abenberg e.V.', 'plz' => '91183', 'email' => 'info@golfclub-abenberg.de' ],
		288 => [ 'name' => 'Golfclub am Nationalpark Bayerischer Wald e.V.', 'plz' => '94568', 'email' => 'info@gcanp.de' ],
		291 => [ 'name' => 'Golfclub Ansbach e.V.', 'plz' => '91598', 'email' => 'info@golf-ansbach.de' ],
		292 => [ 'name' => 'Golfclub Auf der Gsteig Lechbruck am See e.V.', 'plz' => '86983', 'email' => 'info@gsteig.de' ],
		293 => [ 'name' => 'Golfclub Augsburg e.V.', 'plz' => '86399', 'email' => 'info@golfclub-augsburg.de' ],
		301 => [ 'name' => 'Golfclub Bad Wörishofen e.V.', 'plz' => '87668', 'email' => 'info@gc-bw.de' ],
		304 => [ 'name' => 'Golfclub Berchtesgaden e.V.', 'plz' => '83471', 'email' => 'info@golfclub-berchtesgaden.de' ],
		307 => [ 'name' => 'Golfclub Beuerberg e.V.', 'plz' => '82547', 'email' => 'info@gc-beuerberg.de' ],
		326 => [ 'name' => 'Golfclub Dillingen Nusser-Alm GmbH', 'plz' => '89407', 'email' => 'info@gc-dillingen.de' ],
		343 => [ 'name' => 'Golfclub Erlangen e.V.', 'plz' => '91077', 'email' => 'info@gc-erlangen.de' ],
		345 => [ 'name' => 'Golfclub Eschenried e.V.', 'plz' => '85232', 'email' => 'info@golf-eschenried.de' ],
		349 => [ 'name' => 'Golfclub Fahrenbach', 'plz' => '95709', 'email' => 'info@golfclub-fahrenbach.de' ],
		351 => [ 'name' => 'Golfclub Fränkische Schweiz e.V.', 'plz' => '91320', 'email' => 'info@gc-fs.de' ],
		354 => [ 'name' => 'Golfclub Garmisch-Partenkirchen e.V.', 'plz' => '82496', 'email' => 'kontakt@golfclub-gap.de' ],
		379 => [ 'name' => 'Golfclub Hassberge e.V.', 'plz' => '97500', 'email' => 'info@golfclub-hassberge.de' ],
		381 => [ 'name' => 'Golfclub Hauptsmoorwald Bamberg e.V.', 'plz' => '96050', 'email' => 'sekretariat@gc-hauptsmoorwald.de' ],
		386 => [ 'name' => 'Golfclub Hellengerst - Hanusel Hof', 'plz' => '', 'email' => 'info@golf-allgaeu.de' ],
		392 => [ 'name' => 'Golfclub Hof e.V.', 'plz' => '95185', 'email' => 'mail@gc-hof.de' ],
		397 => [ 'name' => 'Golfclub Iffeldorf e.V.', 'plz' => '82393', 'email' => 'info@golfplatz-iffeldorf.de' ],
		400 => [ 'name' => 'Golfclub Isarwinkel e.V.', 'plz' => '83646', 'email' => 'info@gc-isarwinkel.de' ],
		407 => [ 'name' => 'Golfclub Königsbrunn e.V.', 'plz' => '86343', 'email' => 'info@gc-koenigsbrunn.de' ],
		412 => [ 'name' => 'Golfclub Landau/Isar e.V.', 'plz' => '94405', 'email' => 'info@golfpark-landau.de' ],
		413 => [ 'name' => 'Golfclub Landshut e.V.', 'plz' => '84095', 'email' => 'sekretariat@golf-landshut.de' ],
		415 => [ 'name' => 'Golfclub Lauterhofen e.V.', 'plz' => '92283', 'email' => 'info@gc-lauterhofen.de' ],
		416 => [ 'name' => 'Golfclub Lechfeld e.V.', 'plz' => '86343', 'email' => 'info@gclechfeld.de' ],
		417 => [ 'name' => 'Golfclub Leitershofen e.V.', 'plz' => '86391', 'email' => 'gcl@golfclub-leitershofen.de' ],
		419 => [ 'name' => 'Golfclub Lichtenau-Weickershof e.V.', 'plz' => '91586', 'email' => 'info@gclichtenau.de' ],
		422 => [ 'name' => 'Golfclub Main-Spessart, Marktheidenfeld-Eichenfürst e.V.', 'plz' => '97828', 'email' => 'info@gc-msp.de' ],
		427 => [ 'name' => 'Golfclub Maria Bildhausen e.V.', 'plz' => '97702', 'email' => 'info@maria-bildhausen.de' ],
		432 => [ 'name' => 'Golfclub Memmingen Gut Westerhart e.V.', 'plz' => '87740', 'email' => 'info@golfclub-memmingen.de' ],
		438 => [ 'name' => 'Golfclub München Eichenried', 'plz' => '85452', 'email' => 'info@gc-eichenried.de' ],
		439 => [ 'name' => 'Golfclub München Valley e.V.', 'plz' => '83626', 'email' => 'info@golfvalley.de' ],
		440 => [ 'name' => 'Golfclub München-Riedhof e.V.', 'plz' => '82544', 'email' => 'info@riedhof.de' ],
		442 => [ 'name' => 'Golfclub München-West Odelzhausen e.V.', 'plz' => '85235', 'email' => 'info@gcmw.de' ],
		451 => [ 'name' => 'Golfclub Oberstaufen-Steibis e.V.', 'plz' => '87534', 'email' => 'info@golf-oberstaufen.de' ],
		452 => [ 'name' => 'Golfclub Oberstdorf e.V.', 'plz' => '87561', 'email' => 'info@golfclub-oberstdorf.de' ],
		454 => [ 'name' => 'Golfclub Olching e.V.', 'plz' => '82140', 'email' => 'sportbuero@golfclubolching.de' ],
		461 => [ 'name' => 'Golfclub Pfaffing Wasserburger Land e.V.', 'plz' => '83539', 'email' => 'club@gcpwl.de' ],
		469 => [ 'name' => 'Golfclub Reichsstadt Bad Windsheim e.V.', 'plz' => '91438', 'email' => 'kontakt@golf-bw.de' ],
		472 => [ 'name' => 'Golfclub Reit im Winkl e.V.', 'plz' => '6345', 'email' => 'info@gcreit.de' ],
		485 => [ 'name' => 'Golfclub Rottbach e.V.', 'plz' => '82216', 'email' => 'info@rottbach.de' ],
		488 => [ 'name' => 'Golfclub Ruhpolding e.V.', 'plz' => '83324', 'email' => 'info@golfclub-ruhpolding.de' ],
		490 => [ 'name' => 'Golfclub Sagmühle e.V.', 'plz' => '94086', 'email' => 'info@sagmuehle.de' ],
		494 => [ 'name' => 'Golfclub Schloss Egmating', 'plz' => '85658', 'email' => 'empfang@gc-egmating.de' ],
		496 => [ 'name' => 'Golfclub Schloss Guttenburg e.V.', 'plz' => '84559', 'email' => 'info@golfclub-guttenburg.de' ],
		501 => [ 'name' => 'Golfclub Schloß Mainsondheim e.V.', 'plz' => '97337', 'email' => 'info@golf-mainsondheim.de' ],
		506 => [ 'name' => 'Golfclub Schloss Reichertshausen e.V.', 'plz' => '85293', 'email' => 'info@gcr.de' ],
		511 => [ 'name' => 'Golfclub Schloßberg e.V.', 'plz' => '94419', 'email' => 'info@golfclub-schlossberg.de' ],
		516 => [ 'name' => 'Golfclub Schwanhof e.V.', 'plz' => '92706', 'email' => 'info@golfclub-schwanhof.de' ],
		523 => [ 'name' => 'Golfclub Sonnenhof', 'plz' => '93462', 'email' => 'info@sonnenhof-lam.de' ],
		526 => [ 'name' => 'Golfclub Starnberg e.V.', 'plz' => '82319', 'email' => 'club@gcstarnberg.de' ],
		537 => [ 'name' => 'Golfclub Tegernbach e.V.', 'plz' => '82293', 'email' => 'info@gc-tegernbach.de' ],
		563 => [ 'name' => 'Golfclub Zollmühle e.V.', 'plz' => '91792', 'email' => 'info@golfanlage-zollmuehle.de' ],
		564 => [ 'name' => 'Golfclub zu Gut Ludwigsberg e.V.', 'plz' => '', 'email' => 'info@golfclub-tuerkheim.de' ],
		571 => [ 'name' => 'GolfPark Augsburg', 'plz' => '86199', 'email' => 'info@golfpark-augsburg.de' ],
		575 => [ 'name' => 'Golfpark Donauwörth', 'plz' => '86609', 'email' => 'info@golfpark-donauwoerth.de' ],
		577 => [ 'name' => 'GolfPark Gerolsbach', 'plz' => '85302', 'email' => 'info@golfpark-gerolsbach.de' ],
		587 => [ 'name' => 'Golfpark Oberzwieselau e.V.', 'plz' => '94227', 'email' => 'info@golfpark-oberzwieselau.de' ],
		593 => [ 'name' => 'Golfpark Schloßgut Lenzfried', 'plz' => '87437', 'email' => 'info@golfparklenzfried.de' ],
		606 => [ 'name' => 'Golfplatz Leonhardshaun', 'plz' => '84061', 'email' => 'info@golfplatz-leonhardshaun.de' ],
		610 => [ 'name' => 'Golfplatz Stenz', 'plz' => '86975', 'email' => 'golfplatz.stenz@t-online.de' ],
		611 => [ 'name' => 'Golfplatz Tegernsee', 'plz' => '83666', 'email' => 'info@golfplatz-tegernsee.de' ],
		612 => [ 'name' => 'Golfplatz Thailing GmbH & Co. KG', 'plz' => '85643', 'email' => 'info@golfplatz-thailing.de' ],
		617 => [ 'name' => 'GolfRange München-Brunnthal', 'plz' => '85649', 'email' => 'info@golfrange.de' ],
		618 => [ 'name' => 'GolfRange München-Germering Süd', 'plz' => '82110', 'email' => 'info@golfrange.de' ],
		619 => [ 'name' => 'GolfRange Nürnberg', 'plz' => '91189', 'email' => 'info@golfrange.de' ],
		626 => [ 'name' => 'Golfzentrum München-Aschheim', 'plz' => '85609', 'email' => 'info@golf-aschheim.de' ],
		629 => [ 'name' => 'GREEN HILL Der Golf & Eventpark München-Ost', 'plz' => '85609', 'email' => 'info@greenhill-golf.de' ],
		636 => [ 'name' => 'Gut Rieden Sport und Freizeit GmbH', 'plz' => '82319', 'email' => 'info@gut-rieden.de' ],
		647 => [ 'name' => 'Jura Golf e.V. Hilzhofen', 'plz' => '92367', 'email' => 'info@juragolf.de' ],
		656 => [ 'name' => 'Land- und Golf-Club Werdenfels e.V.', 'plz' => '82467', 'email' => 'info@golfclub-werdenfels.de' ],
		664 => [ 'name' => 'MARC AUREL Spa & Golf Resort', 'plz' => '93333', 'email' => 'info@twomedia.biz' ],
		672 => [ 'name' => 'München GolfCity GmbH', 'plz' => '82178', 'email' => 'koeln@golfcity.de' ],
		673 => [ 'name' => 'Münchener Golf-Club e.V.', 'plz' => '82064', 'email' => 'strasslach@mgc-golf.de' ],
		675 => [ 'name' => 'New GolfClub Neu-Ulm', 'plz' => '89233', 'email' => 'info@newgolfclub.de' ],
		686 => [ 'name' => 'Panorama Golf Passau', 'plz' => '94081', 'email' => 'info@panorama-golf.info' ],
		695 => [ 'name' => 'Rottaler Golf- und Country-Club e.V.', 'plz' => '84332', 'email' => 'info@rottaler-gc.de' ],
		703 => [ 'name' => 'Tegernseer Golf-Club Bad Wiessee e.V.', 'plz' => '83707', 'email' => 'info@tegernseer-golf-club.de' ],
		705 => [ 'name' => 'Thermen Golf Bad Füssing-Kirchham e.V.', 'plz' => '94072', 'email' => 'info@thermengolf.de' ],
		707 => [ 'name' => 'Tölzer Golfclub e.V.', 'plz' => '83646', 'email' => 'golf@toelzer-golfclub.de' ],
		719 => [ 'name' => 'Wittelsbacher Golfclub Rohrenfeld-Neuburg e.V.', 'plz' => '86633', 'email' => 'info@wbgc.de' ],
		720 => [ 'name' => 'Zieglers Golfplatz GmbH & Co. KG', 'plz' => '86633', 'email' => 'info@zieglersgolfplatz.de' ],
	];
}

/** @return array<string,array{name:string,plz:string,ort:string,email:string,phone:string,website:string}> Simulator-Key => Kontakt */
function fge_stammdaten_mails_simulators(): array {
	return [
		'0711golfschule esslingen|73728' => [ 'name' => '0711Golfschule Esslingen', 'plz' => '73728', 'ort' => 'Esslingen', 'email' => 'info@0711Golfschule.de', 'phone' => '', 'website' => '' ],
		'adendorf indoor golf|adendorf' => [ 'name' => 'Golf Resort Adendorf Indoor Golf', 'plz' => '', 'ort' => 'Adendorf', 'email' => 'golf@castanea-resort.de', 'phone' => '', 'website' => '' ],
		'adventure indoor golf|72336' => [ 'name' => 'Adventure&Indoor Golf', 'plz' => '72336', 'ort' => 'Balingen', 'email' => 'info@golf-balingen.de', 'phone' => '+49 7433 385990', 'website' => '' ],
		'aloha sport club braunschweig|38122' => [ 'name' => 'Aloha Sport Club Braunschweig', 'plz' => '38122', 'ort' => 'Braunschweig', 'email' => 'aloha-bs@outlook.de', 'phone' => '+49 531 840110', 'website' => '' ],
		'apex indoor golf bonn|53229' => [ 'name' => 'APEX Indoor Golf Bonn', 'plz' => '53229', 'ort' => 'Bonn', 'email' => 'info@apexig.de', 'phone' => '', 'website' => 'https://www.apexig.de/' ],
		'arena 79 bottrop|bottrop' => [ 'name' => 'Arena 79 Bottrop', 'plz' => '', 'ort' => 'Bottrop', 'email' => 'info@arena79.de', 'phone' => '', 'website' => '' ],
		'ball haus reinhausen|gleichen reinhausen' => [ 'name' => 'Ball-Haus Reinhausen', 'plz' => '', 'ort' => 'Gleichen-Reinhausen', 'email' => 'info@ballhaus-reinhausen.de', 'phone' => '', 'website' => '' ],
		'bayreuth|bayreuth' => [ 'name' => 'Golfclub Bayreuth', 'plz' => '', 'ort' => 'Bayreuth', 'email' => 'info@gc-bayreuth.de', 'phone' => '', 'website' => '' ],
		'berliner gatow|berlin' => [ 'name' => 'Berliner Golf Club Gatow', 'plz' => '', 'ort' => 'Berlin', 'email' => 'info@golfclubgatow.de', 'phone' => '', 'website' => '' ],
		'bielefeld indoor range|bielefeld' => [ 'name' => 'Bielefeld Indoor Range', 'plz' => '', 'ort' => 'Bielefeld', 'email' => 'bielefeld@golfhouse.de', 'phone' => '', 'website' => '' ],
		'birdie box hamburg|22869' => [ 'name' => 'Birdie Box Hamburg', 'plz' => '22869', 'ort' => 'Schenefeld', 'email' => 'golf@birdiebox.hamburg', 'phone' => '0155 6070 1852', 'website' => 'https://birdiebox.hamburg/' ],
		'birdies indoor golf nürnberg|90441' => [ 'name' => 'Birdies Indoor Golf Nürnberg', 'plz' => '90441', 'ort' => 'Nürnberg', 'email' => 'kontakt@birdiesgolf.de', 'phone' => '0151 54855925', 'website' => 'https://www.birdiesgolf.de/' ],
		'blauer fasan indoor golf wiesmoor|wiesmoor' => [ 'name' => 'Blauer Fasan Indoor-Golf Wiesmoor', 'plz' => '', 'ort' => 'Wiesmoor', 'email' => 'golf@blauer-fasan.de', 'phone' => '', 'website' => '' ],
		'bruckmannshof|hünxe' => [ 'name' => 'Golfclub Bruckmannshof', 'plz' => '', 'ort' => 'Hünxe', 'email' => 'gc-bruckmannshof@t-online.de', 'phone' => '', 'website' => '' ],
		'brute golf lounge|91596' => [ 'name' => 'Brute Golf Lounge', 'plz' => '91596', 'ort' => 'Burk', 'email' => 'info@brute-golf.com', 'phone' => '+49 160 91952037', 'website' => 'https://www.brutegolflounge.de/' ],
		'bsv hamburg indoor golf|22761' => [ 'name' => 'BSV Hamburg Indoor-Golf', 'plz' => '22761', 'ort' => 'Hamburg', 'email' => 'indoorgolf@bsv-hamburg.de', 'phone' => '', 'website' => '' ],
		'capitol yard golf lounge berlin|10245' => [ 'name' => 'Capitol Yard Golf Lounge Berlin', 'plz' => '10245', 'ort' => 'Berlin', 'email' => 'kontakt@spreespeicher-events.de', 'phone' => '', 'website' => '' ],
		'chigolf the movement code|85662' => [ 'name' => 'chigolf - The Movement Code', 'plz' => '85662', 'ort' => 'Hohenbrunn', 'email' => 'info@chigolf.de', 'phone' => '+49 174 3177050', 'website' => 'https://www.chigolf.de/' ],
		'citygolf center dresden|dresden' => [ 'name' => 'Citygolf Center Dresden', 'plz' => '', 'ort' => 'Dresden', 'email' => 'info@buerogolf-agentur.de', 'phone' => '', 'website' => '' ],
		'club align golf saarbrücken|66117' => [ 'name' => 'Club.align Golf Saarbrücken', 'plz' => '66117', 'ort' => 'Saarbrücken', 'email' => 'info@clubalign-golf.com', 'phone' => '+49 681 58829962', 'website' => '' ],
		'clubhouse nürnberg|90431' => [ 'name' => 'Clubhouse Nürnberg', 'plz' => '90431', 'ort' => 'Nürnberg', 'email' => 'info@clubhouse-nuernberg.de', 'phone' => '+49 911 99996633', 'website' => 'https://clubhouse-nbg.de/' ],
		'cockaynegolf indoor lübeck|lübeck' => [ 'name' => 'CockayneGolf Indoor Lübeck', 'plz' => '', 'ort' => 'Lübeck', 'email' => 'hello@cockayne-golf.de', 'phone' => '', 'website' => '' ],
		'cosmo sports indoorgolf düsseldorf|düsseldorf' => [ 'name' => 'COSMO SPORTS Indoorgolf Düsseldorf', 'plz' => '', 'ort' => 'Düsseldorf', 'email' => 'info@cosmo-sports.de', 'phone' => '', 'website' => '' ],
		'der öschberghof indoor golf|donaueschingen' => [ 'name' => 'Der Öschberghof Indoor Golf', 'plz' => '', 'ort' => 'Donaueschingen', 'email' => 'golf@oeschberghof.com', 'phone' => '', 'website' => '' ],
		'donau passau indoor golf|passau' => [ 'name' => 'Donau Golf Club Passau Indoor Golf', 'plz' => '', 'ort' => 'Passau', 'email' => 'info@golf-passau.de', 'phone' => '', 'website' => '' ],
		'eagleswing indoor golf studio|22159' => [ 'name' => 'Eagleswing Indoor Golf Studio', 'plz' => '22159', 'ort' => 'Hamburg', 'email' => 'team@eagleswing.de', 'phone' => '+49 160 91278162', 'website' => 'https://eagleswing.de/' ],
		'eisen sieben indoor golf|21509' => [ 'name' => 'Eisen Sieben Indoor Golf', 'plz' => '21509', 'ort' => 'Glinde', 'email' => 'info@eisen-sieben.com', 'phone' => '+49 172 3077737', 'website' => 'https://eisen-sieben.com/' ],
		'fairway lounge neustadt wn|92660' => [ 'name' => 'Fairway Lounge Neustadt/WN', 'plz' => '92660', 'ort' => 'Neustadt an der Waldnaab', 'email' => 'info@fairway-lounge.de', 'phone' => '09602 1224', 'website' => 'https://fairway-lounge.de/' ],
		'firstgolf magdeburg|39112' => [ 'name' => 'FIRSTGOLF Magdeburg', 'plz' => '39112', 'ort' => 'Magdeburg', 'email' => 'info@firstgolf-magdeburg.de', 'phone' => '+49 391 4059049', 'website' => '' ],
		'fitness physiotherapie preetz indoor golf|preetz' => [ 'name' => 'Fitness & Physiotherapie Preetz Indoor Golf', 'plz' => '', 'ort' => 'Preetz', 'email' => 'sport@t-sp.de', 'phone' => '', 'website' => '' ],
		'flight alzenau|63755' => [ 'name' => 'FLIGHT Alzenau', 'plz' => '63755', 'ort' => 'Alzenau', 'email' => 'hello@flight-golf.de', 'phone' => '+49 6023 9298570', 'website' => '' ],
		'flyingolf rostock|18069' => [ 'name' => 'Flyingolf Rostock', 'plz' => '18069', 'ort' => 'Rostock', 'email' => 'info@flyingolf.de', 'phone' => '+49 381 12733194', 'website' => '' ],
		'foreyou indoor golf entlocation|76689' => [ 'name' => 'ForeYou Indoor Golf & Eventlocation', 'plz' => '76689', 'ort' => 'Karlsdorf-Neuthard', 'email' => 'info@foreyou.golf', 'phone' => '', 'website' => 'https://www.foreyou.golf/' ],
		'go golf offensive maritim hotel dresden|01067' => [ 'name' => 'GO! Golf-Offensive – Maritim Hotel Dresden', 'plz' => '01067', 'ort' => 'Dresden', 'email' => 'info@golf-offensive.de', 'phone' => '', 'website' => 'https://www.golf-offensive.de/golfsimulator/' ],
		'go indoor dresden waldschlösschen|01099' => [ 'name' => 'GO! Indoor Golfclub Dresden – Waldschlösschen', 'plz' => '01099', 'ort' => 'Dresden', 'email' => 'info@golf-offensive.de', 'phone' => '', 'website' => 'https://www.golf-offensive.de/' ],
		'golf at your best leipzig|04357' => [ 'name' => 'Golf At Your Best Leipzig', 'plz' => '04357', 'ort' => 'Leipzig', 'email' => 'info@golfatyourbest.com', 'phone' => '+49 172 3404482', 'website' => '' ],
		'golf in a box hamburg niendorf|22457' => [ 'name' => 'Golf in a Box Hamburg – Niendorf', 'plz' => '22457', 'ort' => 'Hamburg', 'email' => 'info@golf-in-a-box.de', 'phone' => '+49 151 50562874', 'website' => 'https://golf-in-a-box.de/' ],
		'golf in a box hamburg rotherbaum|20146' => [ 'name' => 'Golf in a Box Hamburg – Rotherbaum', 'plz' => '20146', 'ort' => 'Hamburg', 'email' => 'info@golf-in-a-box.de', 'phone' => '+49 151 50562874', 'website' => 'https://golf-in-a-box.de/' ],
		'golf inside24 leipzig|04347' => [ 'name' => 'Golf-Inside24 Leipzig', 'plz' => '04347', 'ort' => 'Leipzig', 'email' => 'info@golf-inside24.de', 'phone' => '+49 341 2317105', 'website' => '' ],
		'golf life langenfeld|40764' => [ 'name' => 'GOLF LIFE Langenfeld', 'plz' => '40764', 'ort' => 'Langenfeld', 'email' => 'info@golf-life.de', 'phone' => '+49 2173 1065830', 'website' => 'https://www.golf-life.de/' ],
		'golf loft 44|73061' => [ 'name' => 'Golf Loft 44', 'plz' => '73061', 'ort' => 'Ebersbach an der Fils', 'email' => 'info@golfloft44.de', 'phone' => '+49 7163 44688', 'website' => 'https://www.golfloft44.de/' ],
		'golf lounge resort hamburg|hamburg' => [ 'name' => 'Golf Lounge Resort Hamburg', 'plz' => '', 'ort' => 'Hamburg', 'email' => 'mail@golflounge.de', 'phone' => '', 'website' => '' ],
		'golf park dessau|dessau' => [ 'name' => 'Golf-Park Dessau', 'plz' => '', 'ort' => 'Dessau', 'email' => 'info@golfclub-dessau.de', 'phone' => '', 'website' => '' ],
		'golf performance institute berlin|10589' => [ 'name' => 'Golf Performance Institute Berlin', 'plz' => '10589', 'ort' => 'Berlin', 'email' => 'info@gpi-fitting.de', 'phone' => '+49 151 53657941', 'website' => '' ],
		'golf range karben indoor golf|karben' => [ 'name' => 'Golf Range Karben Indoor Golf', 'plz' => '', 'ort' => 'Karben', 'email' => 'info@golfrange-karben.de', 'phone' => '', 'website' => '' ],
		'golf simulator gunzenhausen|gunzenhausen' => [ 'name' => 'Golf Simulator Gunzenhausen', 'plz' => '', 'ort' => 'Gunzenhausen', 'email' => 'info@golfsimgun.de', 'phone' => '', 'website' => '' ],
		'golf studio berlin|10587' => [ 'name' => 'Golf Studio Berlin', 'plz' => '10587', 'ort' => 'Berlin', 'email' => 'hello@hohmann-golf.de', 'phone' => '+49 30 39800980', 'website' => '' ],
		'golf usa vr golf garching|85748' => [ 'name' => 'Golf USA - VR Golf Garching', 'plz' => '85748', 'ort' => 'Garching', 'email' => 'info@golfusa-munich.com', 'phone' => '', 'website' => '' ],
		'golf valley|valley' => [ 'name' => 'Golf Valley', 'plz' => '', 'ort' => 'Valley', 'email' => 'info@golfvalley.de', 'phone' => '', 'website' => '' ],
		'golf welt hochrhein|' => [ 'name' => 'Golf-Welt Hochrhein', 'plz' => '', 'ort' => '', 'email' => 'info@golfwelt-hochrhein.de', 'phone' => '', 'website' => '' ],
		'golfakademie leipzig|leipzig' => [ 'name' => 'Golfakademie Leipzig', 'plz' => '', 'ort' => 'Leipzig', 'email' => 'kessler@golfakademie.pro', 'phone' => '', 'website' => '' ],
		'golfersworld moosinning|85452' => [ 'name' => 'Golfersworld Moosinning', 'plz' => '85452', 'ort' => 'Moosinning', 'email' => 'info@golfersworld.de', 'phone' => '', 'website' => '' ],
		'golfhalle münsterland|59394' => [ 'name' => 'Golfhalle Münsterland', 'plz' => '59394', 'ort' => 'Nordkirchen', 'email' => 'info@golfhalle-muensterland.de', 'phone' => '+49 173 4444905', 'website' => '' ],
		'golfhaus unterwössen|unterwössen' => [ 'name' => 'Golfhaus Unterwössen', 'plz' => '', 'ort' => 'Unterwössen', 'email' => 'temp@golfhaus.de', 'phone' => '', 'website' => '' ],
		'golfhub indoor golf lounge chemnitz|09125' => [ 'name' => 'GOLFHUB Indoor Golf Lounge Chemnitz', 'plz' => '09125', 'ort' => 'Chemnitz', 'email' => 'info@golfhub.de', 'phone' => '+49 371 56070884', 'website' => 'https://www.golfhub.de/' ],
		'golfinn indoor golf loft wuppertal|42369' => [ 'name' => 'GOLFINN | Indoor-Golf Loft Wuppertal', 'plz' => '42369', 'ort' => 'Wuppertal', 'email' => 'm.odendahl@golf-inn.de', 'phone' => '0175 4820027', 'website' => 'https://www.golf-inn.de/' ],
		'golflounge bamberg|bamberg' => [ 'name' => 'Golflounge Bamberg', 'plz' => '', 'ort' => 'Bamberg', 'email' => 'golfloungebamberg@ebusy.de', 'phone' => '', 'website' => '' ],
		'golfpark bostalsee|nohfelden' => [ 'name' => 'Golfpark Bostalsee', 'plz' => '', 'ort' => 'Nohfelden', 'email' => 'info@golfpark-bostalsee.de', 'phone' => '', 'website' => '' ],
		'golfpark gudensberg|gudensberg' => [ 'name' => 'Golfpark Gudensberg', 'plz' => '', 'ort' => 'Gudensberg', 'email' => 'info@golfpark-gudensberg.de', 'phone' => '', 'website' => '' ],
		'golfpark neustadt harz|neustadt harz' => [ 'name' => 'Golfpark Neustadt/Harz', 'plz' => '', 'ort' => 'Neustadt/Harz', 'email' => 'indoor@golfpark-neustadt.de', 'phone' => '', 'website' => '' ],
		'golfpark schloßgut lenzfried|kempten' => [ 'name' => 'Golfpark Schloßgut Lenzfried', 'plz' => '', 'ort' => 'Kempten', 'email' => 'info@golfparklenzfried.de', 'phone' => '', 'website' => '' ],
		'golfschule köln|köln' => [ 'name' => 'Golfschule Köln', 'plz' => '', 'ort' => 'Köln', 'email' => 'info@golfschule-koeln.de', 'phone' => '', 'website' => '' ],
		'golfschule pro shop hendrik harms|26871' => [ 'name' => 'Golfschule & Pro Shop Hendrik Harms', 'plz' => '26871', 'ort' => 'Papenburg', 'email' => 'info@hennygolf.de', 'phone' => '', 'website' => '' ],
		'golftempel berlin|berlin' => [ 'name' => 'Golftempel Berlin', 'plz' => '', 'ort' => 'Berlin', 'email' => 'info@golftempel.de', 'phone' => '+49 152 33978290', 'website' => 'https://golftempel.de/' ],
		'gr enmühle|ratingen' => [ 'name' => 'Golfclub Grevenmühle', 'plz' => '', 'ort' => 'Ratingen', 'email' => 'golfclub@grevenmuehle.de', 'phone' => '', 'website' => '' ],
		'green box bad kreuznach|55545' => [ 'name' => 'GREEN BOX Bad Kreuznach', 'plz' => '55545', 'ort' => 'Bad Kreuznach', 'email' => 'info@greenbox-sportlounge.de', 'phone' => '+49 671 79 66 90 0', 'website' => '' ],
		'green grid|22303' => [ 'name' => 'Green Grid Golf Club', 'plz' => '22303', 'ort' => 'Hamburg', 'email' => 'club@green-grid-golf.de', 'phone' => '+49 40 6360768811', 'website' => 'https://green-grid-golf.de/' ],
		'gtpc eisenach|eisenach' => [ 'name' => 'GTPC Eisenach', 'plz' => '', 'ort' => 'Eisenach', 'email' => 'info@golfcenter-eisenach.de', 'phone' => '', 'website' => '' ],
		'hamburger golfakademie|hamburg' => [ 'name' => 'Hamburger Golfakademie', 'plz' => '', 'ort' => 'Hamburg', 'email' => 'info@hamburger-golfakademie.de', 'phone' => '', 'website' => '' ],
		'herzogenaurach|herzogenaurach' => [ 'name' => 'Golfclub Herzogenaurach', 'plz' => '', 'ort' => 'Herzogenaurach', 'email' => 'info@golfclub-herzogenaurach.de', 'phone' => '', 'website' => '' ],
		'hio fitting hamburg|20146' => [ 'name' => 'HIO Fitting Hamburg', 'plz' => '20146', 'ort' => 'Hamburg', 'email' => 'hamburg@hio-fitting.de', 'phone' => '+49 89 96030575', 'website' => 'https://hio-fitting.de/hamburg/' ],
		'hohmanngolf indoorgolf berlin|berlin' => [ 'name' => 'HohmannGolf Indoorgolf Berlin', 'plz' => '', 'ort' => 'Berlin', 'email' => 'service@hohmann-golf.de', 'phone' => '', 'website' => '' ],
		'hotel central hof|hof' => [ 'name' => 'Hotel Central Hof', 'plz' => '', 'ort' => 'Hof', 'email' => 'info@hotel-central-hof.de', 'phone' => '', 'website' => '' ],
		'hotel haus schnepper indoor golf|attendorn' => [ 'name' => 'Hotel Haus Schnepper Indoor Golf', 'plz' => '', 'ort' => 'Attendorn', 'email' => 'hotel-info@hotel-schnepper.de', 'phone' => '', 'website' => '' ],
		'hotel residence starnberger see indoor golf|feldafing' => [ 'name' => 'Hotel Residence Starnberger See Indoor Golf', 'plz' => '', 'ort' => 'Feldafing', 'email' => 'info@residence-starnberg.de', 'phone' => '', 'website' => '' ],
		'indoor berlin golfzentrum berlin schöneberg|10829' => [ 'name' => 'Indoor Golf Club Berlin / Golfzentrum Berlin Schöneberg', 'plz' => '10829', 'ort' => 'Berlin', 'email' => 'info@golfzentrumberlin.de', 'phone' => '+49 30 81828500', 'website' => 'https://www.golfzentrumberlin.de/' ],
		'indoor golf center bad münstereifel|bad münstereifel' => [ 'name' => 'Indoor Golf Center Bad Münstereifel', 'plz' => '', 'ort' => 'Bad Münstereifel', 'email' => 'info@sportwelt-schaefer.de', 'phone' => '', 'website' => '' ],
		'indoor golf center berlin ku damm|berlin' => [ 'name' => 'Indoor Golf Center Berlin Ku’damm', 'plz' => '', 'ort' => 'Berlin', 'email' => 'info@indoor-golf-center.de', 'phone' => '', 'website' => '' ],
		'indoor golf chemnitz erzberger straße|chemnitz' => [ 'name' => 'Indoor Golf Chemnitz – Erzberger Straße', 'plz' => '', 'ort' => 'Chemnitz', 'email' => 'info@indoorgolf-chemnitz.de', 'phone' => '', 'website' => '' ],
		'indoor golf duderstadt|37115' => [ 'name' => 'Indoor Golf Duderstadt', 'plz' => '37115', 'ort' => 'Duderstadt', 'email' => 'Golf@Mueller-Duderstadt.de', 'phone' => '+49 5527 3227', 'website' => '' ],
		'indoor golf erfurt|99094' => [ 'name' => 'Indoor Golf Erfurt', 'plz' => '99094', 'ort' => 'Erfurt', 'email' => 'kontakt@indoor-golf-erfurt.de', 'phone' => '+49 171 6439567', 'website' => '' ],
		'indoor golf grafing|grafing' => [ 'name' => 'Indoor Golf Grafing', 'plz' => '', 'ort' => 'Grafing', 'email' => 'info@indoorgolfgrafing.de', 'phone' => '', 'website' => '' ],
		'indoor golf hohenloher tor|74626' => [ 'name' => 'Indoor Golf Hohenloher Tor', 'plz' => '74626', 'ort' => 'Bretzfeld', 'email' => 'info@hohenlohertor.de', 'phone' => '+49 7946 9467640', 'website' => '' ],
		'indoor golf lounge kronberg|61476' => [ 'name' => 'Indoor Golf & Lounge Kronberg', 'plz' => '61476', 'ort' => 'Kronberg', 'email' => 'office@indoorgolf-kronberg.de', 'phone' => '', 'website' => '' ],
		'indoor golf mannheim 77|68309' => [ 'name' => 'Indoor Golf Mannheim 77', 'plz' => '68309', 'ort' => 'Mannheim', 'email' => 'golfshopnopro@web.de', 'phone' => '+49 151 42610130', 'website' => '' ],
		'indoor golf marhördt marhördt|oberrot marhördt' => [ 'name' => 'Indoor Golf Marhördt / Golfclub Marhördt', 'plz' => '', 'ort' => 'Oberrot-Marhördt', 'email' => 'info@golfclub-marhoerdt.de', 'phone' => '', 'website' => '' ],
		'indoor golf mudau mudau|mudau' => [ 'name' => 'Indoor Golf Mudau / Golfclub Mudau', 'plz' => '', 'ort' => 'Mudau', 'email' => 'info@golfclub-mudau.de', 'phone' => '', 'website' => '' ],
		'indoor golf oberhof|98559' => [ 'name' => 'Indoor Golf Oberhof', 'plz' => '98559', 'ort' => 'Oberhof', 'email' => 'info@physiofit-am-rennsteig.de', 'phone' => '', 'website' => '' ],
		'indoor golf rottal|84381' => [ 'name' => 'Indoor Golf Rottal', 'plz' => '84381', 'ort' => 'Johanniskirchen', 'email' => 'paullamprecht@t-online.de', 'phone' => '', 'website' => 'https://www.indoor-golf-rottal.com/' ],
		'indoor golf ruhrpott|45475' => [ 'name' => 'Indoor-Golf-Ruhrpott', 'plz' => '45475', 'ort' => 'Mülheim an der Ruhr', 'email' => 'info@indoor-golf-ruhrpott.de', 'phone' => '0208 45798275', 'website' => 'https://trackrange.golf/indoor-golf-ruhrpott/' ],
		'indoor golf sauerland|' => [ 'name' => 'Indoor-Golf Sauerland', 'plz' => '', 'ort' => '', 'email' => 'tennishalle-sundern@t-online.de', 'phone' => '', 'website' => '' ],
		'indoor golfarena greifswald|greifswald' => [ 'name' => 'Indoor-Golfarena Greifswald', 'plz' => '', 'ort' => 'Greifswald', 'email' => 'indoor.golf@gmx.de', 'phone' => '', 'website' => '' ],
		'indoorgolf alberthausen|bad kissingen' => [ 'name' => 'Indoorgolf Alberthausen', 'plz' => '', 'ort' => 'Bad Kissingen', 'email' => 'wolfgang@seufert-bk.de', 'phone' => '', 'website' => '' ],
		'indoorgolf braunfels|braunfels' => [ 'name' => 'Indoorgolf Braunfels', 'plz' => '', 'ort' => 'Braunfels', 'email' => 'info@indoorgolf-braunfels.de', 'phone' => '', 'website' => '' ],
		'indoorgolf büren|büren' => [ 'name' => 'Indoorgolf Büren', 'plz' => '', 'ort' => 'Büren', 'email' => 'ackfeld@aol.com', 'phone' => '', 'website' => '' ],
		'indoorgolf dresden bannewitz|bannewitz' => [ 'name' => 'Indoorgolf Dresden Bannewitz', 'plz' => '', 'ort' => 'Bannewitz', 'email' => 'service@deingolfshop.de', 'phone' => '', 'website' => '' ],
		'indoorgolf maarheide|niederdürenbach' => [ 'name' => 'Indoorgolf Maarheide', 'plz' => '', 'ort' => 'Niederdürenbach', 'email' => 'info@neuer-maarhof.de', 'phone' => '', 'website' => '' ],
		'indoorgolf münchen west|germering' => [ 'name' => 'Indoorgolf München-West', 'plz' => '', 'ort' => 'Germering', 'email' => 'trainingscenter@indoorgolfmuenchen.de', 'phone' => '', 'website' => '' ],
		'indoorgolf wanfried|wanfried' => [ 'name' => 'Indoorgolf Wanfried', 'plz' => '', 'ort' => 'Wanfried', 'email' => 'wolfgangbeckers@me.com', 'phone' => '', 'website' => '' ],
		'ingolstadt indoor halle|ingolstadt' => [ 'name' => 'GC Ingolstadt Indoor-Halle', 'plz' => '', 'ort' => 'Ingolstadt', 'email' => 'info@golf-ing.de', 'phone' => '', 'website' => '' ],
		'intrago indoor golf münchen perlach|81737' => [ 'name' => 'intrago Indoor Golf München-Perlach', 'plz' => '81737', 'ort' => 'München', 'email' => 'info@intrago.golf', 'phone' => '+49 89 30908400', 'website' => '' ],
		'jordan golfdom köln|köln' => [ 'name' => 'Jordan Golfdom Köln', 'plz' => '', 'ort' => 'Köln', 'email' => 'info@golfdom.de', 'phone' => '', 'website' => '' ],
		'ka2 indoor golf kulmbach|kulmbach' => [ 'name' => 'KA2 Indoor Golf Kulmbach', 'plz' => '', 'ort' => 'Kulmbach', 'email' => 'info@ka2-fitness.de', 'phone' => '', 'website' => '' ],
		'kim golf essen kim screen golf berlin|10555' => [ 'name' => 'Kim Golf & Essen / Kim Screen Golf Berlin', 'plz' => '10555', 'ort' => 'Berlin', 'email' => 'kimscreengolf@gmail.com', 'phone' => '+49 30 20009500', 'website' => '' ],
		'kineto indoor golf bar meerbusch|40667' => [ 'name' => 'KINETO Indoor Golf & Bar Meerbusch', 'plz' => '40667', 'ort' => 'Meerbusch', 'email' => 'info@kineto.golf', 'phone' => '+49 176 11146023', 'website' => 'https://www.kineto.golf/' ],
		'kirchheim wendlingen wernau|kirchheim unter teck' => [ 'name' => 'Golfanlage Kirchheim-Wendlingen-Wernau', 'plz' => '', 'ort' => 'Kirchheim unter Teck', 'email' => 'info@golf-kirchheim.de', 'phone' => '', 'website' => '' ],
		'kölner indoor golf|köln' => [ 'name' => 'Kölner Golfclub Indoor Golf', 'plz' => '', 'ort' => 'Köln', 'email' => 'proshop.koelner-golfclub@golfhouse.de', 'phone' => '', 'website' => '' ],
		'lazy golf hamburg|22177' => [ 'name' => 'LAZY GOLF Hamburg', 'plz' => '22177', 'ort' => 'Hamburg', 'email' => 'info@lazygolf.de', 'phone' => '+49 155 69189134', 'website' => 'https://www.lazygolf.de/' ],
		'mainzer indoor golf|mainz' => [ 'name' => 'Mainzer Golfclub Indoor-Golf', 'plz' => '', 'ort' => 'Mainz', 'email' => 'info@mainzer-golfclub.de', 'phone' => '', 'website' => '' ],
		'maritim golfpark ostsee indoor golf|' => [ 'name' => 'Maritim Golfpark Ostsee Indoor Golf', 'plz' => '', 'ort' => '', 'email' => 'info.golf@maritimgolfpark.de', 'phone' => '', 'website' => '' ],
		'matchplay indoor golf göttingen|37077' => [ 'name' => 'MatchPlay Indoor Golf Göttingen', 'plz' => '37077', 'ort' => 'Göttingen', 'email' => 'webmaster@matchplaygolf.de', 'phone' => '+49 551 30668800', 'website' => 'https://www.matchplaygolf.de/' ],
		'myclubmaker golf it|71296' => [ 'name' => 'myclubmaker Golf+IT', 'plz' => '71296', 'ort' => 'Heimsheim', 'email' => 'info@myclubmaker.de', 'phone' => '+49 7033 4691991', 'website' => '' ],
		'nate danner golf indoor studio reinickendorf|13403' => [ 'name' => 'Nate Danner Golf - Indoor Studio Reinickendorf', 'plz' => '13403', 'ort' => 'Berlin', 'email' => 'natedanner@pga.com', 'phone' => '', 'website' => 'https://www.natedannergolf.com/' ],
		'nate danner golf indoor studio schöneberg|10777' => [ 'name' => 'Nate Danner Golf - Indoor Studio Schöneberg', 'plz' => '10777', 'ort' => 'Berlin', 'email' => 'natedanner@pga.com', 'phone' => '', 'website' => 'https://www.natedannergolf.com/' ],
		'new golf lounge neu ulm|89233' => [ 'name' => 'NEW GOLF LOUNGE Neu-Ulm', 'plz' => '89233', 'ort' => 'Neu-Ulm', 'email' => 'info@newgolfclub.de', 'phone' => '+49 731 70533315', 'website' => '' ],
		'next golf münster|48153' => [ 'name' => 'Next Golf Münster', 'plz' => '48153', 'ort' => 'Münster', 'email' => 'info@next-golf.de', 'phone' => '01578 5134742', 'website' => 'https://next-golf.de/' ],
		'ogolf berlin|10557' => [ 'name' => 'EvoGolf Berlin', 'plz' => '10557', 'ort' => 'Berlin', 'email' => 'kontakt@evogolf.de', 'phone' => '030 20674844 / 0171 7429333', 'website' => 'https://www.evogolf.de/' ],
		'parkhotel stuttgart messe airport|leinfelden echterdingen' => [ 'name' => 'PARKHOTEL STUTTGART MESSE-AIRPORT', 'plz' => '', 'ort' => 'Leinfelden-Echterdingen', 'email' => 'Info@Parkhotel-Stuttgart.de', 'phone' => '', 'website' => '' ],
		'pato golf münchen|80802' => [ 'name' => 'PATO Golf München', 'plz' => '80802', 'ort' => 'München', 'email' => 'golf@patoclub.de', 'phone' => '+49 89 38667028', 'website' => 'https://golf.patoclub.de/de' ],
		'pfaffing wasserburger land|pfaffing' => [ 'name' => 'Golfclub Pfaffing Wasserburger Land', 'plz' => '', 'ort' => 'Pfaffing', 'email' => 'club@gcpwl.de', 'phone' => '', 'website' => '' ],
		'pitching zone lübeck|23560' => [ 'name' => 'Pitching Zone Lübeck', 'plz' => '23560', 'ort' => 'Lübeck', 'email' => 'info@pitching-zone.de', 'phone' => '', 'website' => 'https://pitching-zone.de/' ],
		'pro marine gottmadingen|78244' => [ 'name' => 'Pro Marine Gottmadingen', 'plz' => '78244', 'ort' => 'Gottmadingen', 'email' => 'promarine@promarine.de', 'phone' => '+49 7731 3191319', 'website' => '' ],
		'progolf berlin|10785' => [ 'name' => 'ProGolf Berlin', 'plz' => '10785', 'ort' => 'Berlin', 'email' => 'info@progolfberlin.com', 'phone' => '+49 30 98392628', 'website' => '' ],
		'quellness bad griesbach|bad griesbach' => [ 'name' => 'Quellness & Golf Resort Bad Griesbach', 'plz' => '', 'ort' => 'Bad Griesbach', 'email' => 'golfresort@quellness-golf.com', 'phone' => '', 'website' => '' ],
		'ruff golf dreieich|63303' => [ 'name' => 'RUFF Golf Dreieich', 'plz' => '63303', 'ort' => 'Dreieich', 'email' => 'dreieich@ruffgolf.de', 'phone' => '+49 6103 7894071', 'website' => 'https://ruffgolf.eu/de/' ],
		'ruff golf düsseldorf|40547' => [ 'name' => 'RUFF Golf Düsseldorf', 'plz' => '40547', 'ort' => 'Düsseldorf', 'email' => 'duesseldorf@ruffgolf.de', 'phone' => '+49 173 4231828', 'website' => 'https://ruffgolf.eu/de/' ],
		'ruff indoor golf ostsee|23684' => [ 'name' => 'RUFF Indoor-Golf Ostsee', 'plz' => '23684', 'ort' => 'Scharbeutz', 'email' => 'ostsee@ruffgolf.de', 'phone' => '+49 155 61704576', 'website' => 'https://ruffgolf.eu/de/' ],
		's en tees brunnthal|85649' => [ 'name' => 'Seven Tees Brunnthal', 'plz' => '85649', 'ort' => 'Brunnthal', 'email' => 'brunnthal@seventees.golf', 'phone' => '+49 89 26207031', 'website' => 'https://seventees.golf/' ],
		's en tees köln hürth|50354' => [ 'name' => 'Seven Tees Köln / Hürth', 'plz' => '50354', 'ort' => 'Hürth', 'email' => 'koeln@seventees.golf', 'phone' => '+49 2233 9623993', 'website' => 'https://seventees.golf/' ],
		's en tees münchen|80807' => [ 'name' => 'Seven Tees München', 'plz' => '80807', 'ort' => 'München', 'email' => 'muenchen@seventees.golf', 'phone' => '+49 89 35061940', 'website' => 'https://seventees.golf/' ],
		's en tees olching|82140' => [ 'name' => 'Seven Tees Olching', 'plz' => '82140', 'ort' => 'Olching', 'email' => 'olching@seventees.golf', 'phone' => '+49 8142 66932222', 'website' => 'https://seventees.golf/' ],
		'schloss langenstein|orsingen nenzingen' => [ 'name' => 'Schloss Langenstein', 'plz' => '', 'ort' => 'Orsingen-Nenzingen', 'email' => 'golf-sekretariat@schloss-langenstein.com', 'phone' => '', 'website' => '' ],
		'schopfheim|schopfheim' => [ 'name' => 'Golfanlage Schopfheim', 'plz' => '', 'ort' => 'Schopfheim', 'email' => 'post@golfanlage-schopfheim.de', 'phone' => '', 'website' => '' ],
		'shank brothers|83134' => [ 'name' => 'Shank Brothers', 'plz' => '83134', 'ort' => 'Prutting', 'email' => 'trackman@shank-brothers.de', 'phone' => '+49 151 74269145', 'website' => 'https://shank-brothers.com/' ],
		'sieben welten indoor golf|künzell' => [ 'name' => 'Sieben Welten Indoor Golf', 'plz' => '', 'ort' => 'Künzell', 'email' => 'info@siebenwelten.de', 'phone' => '', 'website' => '' ],
		'sportcenter kautz köln|50939' => [ 'name' => 'Sportcenter Kautz Köln', 'plz' => '50939', 'ort' => 'Köln', 'email' => 'indoorgolfcenter@aol.com', 'phone' => '', 'website' => '' ],
		'sportklamser ulm|ulm' => [ 'name' => 'Sportklamser Ulm', 'plz' => '', 'ort' => 'Ulm', 'email' => 'info@sportklamser-ulm.de', 'phone' => '', 'website' => '' ],
		'sportpalast singen|78224' => [ 'name' => 'Sportpalast Singen', 'plz' => '78224', 'ort' => 'Singen', 'email' => 'info@sportpalast-singen.de', 'phone' => '+49 7731 922450', 'website' => '' ],
		'sportpark offenthal|63303' => [ 'name' => 'Sportpark Offenthal', 'plz' => '63303', 'ort' => 'Dreieich', 'email' => 'fun@sportpark-offenthal.de', 'phone' => '+49 171 1978376', 'website' => '' ],
		'sportpark weißenthurm|weißenthurm' => [ 'name' => 'Sportpark Weißenthurm', 'plz' => '', 'ort' => 'Weißenthurm', 'email' => 'info@sportparkweissenthurm.de', 'phone' => '', 'website' => '' ],
		'sportspark cologne|51149' => [ 'name' => 'SPORTSPARK Cologne', 'plz' => '51149', 'ort' => 'Köln', 'email' => 'golf@cologne-sportspark.de', 'phone' => '+49 2203 980200', 'website' => '' ],
		'st leon rot|st leon rot' => [ 'name' => 'Golf Club St. Leon-Rot', 'plz' => '', 'ort' => 'St. Leon-Rot', 'email' => 'info@gc-slr.de', 'phone' => '', 'website' => '' ],
		'sweetspot cologne|50171' => [ 'name' => 'Sweetspot Cologne', 'plz' => '50171', 'ort' => 'Kerpen', 'email' => 'info@sweetspot-cologne.de', 'phone' => '+49 176 41608680', 'website' => '' ],
		'tap inn golf lounge wasserburg|83512' => [ 'name' => 'Tap Inn Golf Lounge Wasserburg', 'plz' => '83512', 'ort' => 'Wasserburg am Inn', 'email' => 'info@tapinn.de', 'phone' => '', 'website' => 'https://www.tapinn.de/' ],
		'team spieckerhoff indoorgolf|40764' => [ 'name' => 'Team Spieckerhoff Indoorgolf', 'plz' => '40764', 'ort' => 'Langenfeld', 'email' => 'info@team-spieckerhoff.de', 'phone' => '+49 2173 2699154', 'website' => 'https://team-spieckerhoff.de/' ],
		'tee it up hamburg|22419' => [ 'name' => 'Tee It Up Hamburg', 'plz' => '22419', 'ort' => 'Hamburg', 'email' => 'info@teeitupgolf.de', 'phone' => '', 'website' => 'https://www.teeitupgolf.de/' ],
		'tennis center keferloh|grasbrunn' => [ 'name' => 'Tennis Center Keferloh', 'plz' => '', 'ort' => 'Grasbrunn', 'email' => 'tenniscenterkeferloh@yahoo.com', 'phone' => '', 'website' => '' ],
		'tennispark lichtenfels|96215' => [ 'name' => 'Tennispark Lichtenfels', 'plz' => '96215', 'ort' => 'Lichtenfels', 'email' => 'info@tennispark-lichtenfels.de', 'phone' => '+49 9571 2259', 'website' => '' ],
		'the golf loft bensheim|64625' => [ 'name' => 'The Golf Loft Bensheim', 'plz' => '64625', 'ort' => 'Bensheim', 'email' => 'info@thegolfloft.de', 'phone' => '06251 5503853', 'website' => 'https://www.thegolfloft.de/' ],
		'tour green indoor golf center|96173' => [ 'name' => 'TOUR GREEN Indoor Golf Center', 'plz' => '96173', 'ort' => 'Oberhaid', 'email' => 'info@tourgreen.de', 'phone' => '+49 9503 5088920', 'website' => '' ],
		'trackme beach hamburg golf loft|22049' => [ 'name' => 'TrackMe Beach Hamburg Golf-Loft', 'plz' => '22049', 'ort' => 'Hamburg', 'email' => 'info@trackme.de', 'phone' => '', 'website' => 'https://trackme.de/beach' ],
		'trackme hamburg|22761' => [ 'name' => 'TrackMe Hamburg', 'plz' => '22761', 'ort' => 'Hamburg', 'email' => 'info@trackme.de', 'phone' => '+49 40 72551848', 'website' => 'https://trackme.de/' ],
		'vegas bowling und golf lübeck|lübeck' => [ 'name' => 'Vegas Bowling und Golf Lübeck', 'plz' => '', 'ort' => 'Lübeck', 'email' => 'info@vegas-luebeck.de', 'phone' => '', 'website' => '' ],
		'vybe golfstudio saarbrücken|66123' => [ 'name' => 'VYBE Golfstudio Saarbrücken', 'plz' => '66123', 'ort' => 'Saarbrücken', 'email' => 'info@vybegolf.de', 'phone' => '0681 83049280 / 0178 9822500', 'website' => 'https://vybegolf.de/' ],
		'wellnesshotel the grand ahrenshoop|ahrenshoop' => [ 'name' => 'Wellnesshotel THE GRAND Ahrenshoop', 'plz' => '', 'ort' => 'Ahrenshoop', 'email' => 'info-spa@the-grand.de', 'phone' => '', 'website' => '' ],
		'x flex golf kaltenkirchen|24568' => [ 'name' => 'X-Flex Golf Kaltenkirchen', 'plz' => '24568', 'ort' => 'Kaltenkirchen', 'email' => 'info@x-flexgolf.de', 'phone' => '+49 4191 7034258', 'website' => 'https://www.x-flexgolf.de/' ],
		'zollmühle indoor golf|' => [ 'name' => 'Golfanlage Zollmühle Indoor Golf', 'plz' => '', 'ort' => '', 'email' => 'info@golfanlage-zollmuehle.de', 'phone' => '', 'website' => '' ],
	];
}
